### ISSUE TITLE
Is there a way to add prefix globally to avoid conflicts

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#1001]
Hi Team, While generating cmdlets , I have a requirement where each cmdlet's verb needs to have 'CV' prefix in them. For example : Get-ResourcePool needs to be Get-CVResourcePool. Is there a directive that I can add to get this

**Comment by dolauli** [comment]
Please see https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#prefix-subject-prefix-and-subject.

**Comment by JnaneshD05** [comment]
Thanks for the help. Another query we have is have we, Can we include certain external ps1 files which are completely in native powershell into custom folder to bundle together?
