### ISSUE TITLE
Adding new ps1 files to the exports folder or custom folder doesn't get recognised when we build the module

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#1006]
Hi Team,
I am working on adding additional powershell native ps1 files into exports folder which aren't recognised if we execute run_module.ps1 . Please suggest what can be done to achieve this. Thanks in advance

**Comment by JnaneshD05** [comment]
I also tried adding the simple ps1 file to the custom folder and rebuilt using the build-module.ps1 but still the function is not exported

**Comment by JnaneshD05** [comment]
https://github.com/Azure/autorest.powershell/blob/main/docs/customization.md#adding-a-single-variant

**Comment by dolauli** [comment]
It is supported. And I guess you did not add following attribute for the function you want to export.
```
 [CmdletBinding(PositionalBinding=$false)]
```
