### ISSUE TITLE
Empty fields are shown in the output due to optional model members

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#1009]
Hi Team , For a model with lot of optional members, all the members are shown empty instead of ignoring them. Is there a config that could have been added here

--
PS C:\cvpowers\CommvaultPowerShell [CommvaultPowerShell]> $aaa.LaptopPlan.BackupDestinations

BackupStartTime                                : 
BackupsToCopy                                  : 
CopyType                                       : SYNCHRONOUS
CopyTypeName                                   : 
FirstExtendedRetentionRuleIsInfiniteRetention  : 
FirstExtendedRetentionRuleRetentionPeriodDays  : 
FirstExtendedRetentionRuleType                 : 
IsDefault                                      : True
IsMirrorCopy                                   : 
IsSnapCopy                                     : 
Mappings                                       : 
NetAppCloudTarget                              : 
PlanBackupDestinationId                        : 374
PlanBackupDestinationName                      : Primary
RegionDisplayName                              : 
RegionId                                       : 
RegionName                                     : 
RetentionPeriodDays                            : 90
RetentionRuleType                              : RETENTION_PERIOD
SecondExtendedRetentionRuleIsInfiniteRetention : 
SecondExtendedRetentionRuleRetentionPeriodDays :

**Comment by dolauli** [comment]
Currently, it is not supported.
