### ISSUE TITLE
allOf'/'anyOf'/'oneOf' aren't recognised 

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#1018]
Models which have definitions with allof anyof oneof are not generated properly and response isn't shown to the end user . What can be done here to solve this?

**Comment by JnaneshD05** [comment]
Even for POST requests payload itself aren't taken in the generated cmdlet in input which is using oneof.

**Comment by JnaneshD05** [comment]
Hi Team, Any update on this issue? @dolauli . Lot of commands are using the OpenAPI3 specs to document the payloads and models

**Comment by dolauli** [comment]
**allof** is supported, but neither **oneof** nor **anyof** are not supported, and currently, there are no plan to support them.
