### ISSUE TITLE
Compilation Error CS1056

### ISSUE THREAD

**Issue by chniter** [Azure/autorest.powershell#1032]
The compilation error is on {$host}

`var _url = new global::System.Uri($"{$host}{pathAndQuery}");`

![image](https://user-images.githubusercontent.com/2734864/203100434-69a87ced-d9ad-4c3b-a08c-ea15e270d3cb.png)

**Comment by alexrgreenwood** [comment]
@chniter i got this same error and was able to progress by adding a "servers" section to the json

`  "servers": [
    {
      "url": "https://localhost:7145"
    }
  ],`
