### ISSUE TITLE
Switch Params not working : How to remove them?

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#1040]
Hi ,
Our generated SDK has switch params for the boolean schema model. It only passes true value to body when it is passed. We need it to be used both the ways. Can anyone please let me know if I can pass an option not to avoid creating switch params. Can we just have normal positional param ?

**Comment by JnaneshD05** [comment]
@dolauli Please help with this. Is there any way we can make boolean as normal input instead of hastable.

**Comment by JnaneshD05** [comment]
Hi Team, Can anyone Please check and suggest this? @dingmeng-xue

**Comment by JnaneshD05** [comment]
Hi @dolauli , Please find the info. Any switch param generated via the boolean schema model which is converted to switch param, doesn't pass false value if it not passed. We need a functionality where we can pass the false value also. Please check. Thanks for the help. 
SDK Link : https://github.com/Commvault/CVPowershellSDKV2/tree/2022E https://www.powershellgallery.com/packages/CommvaultPowerShell/0.2.11 
Uploading the text file instead of yaml. I generate using cmdline  : **autorest Configuration1.yaml --namespace="Commvault.Powershell" --clear-output-folder --output-folder="C:\cvpowers\CommvaultPowerShell" --powershell --input-file=OpenAPI3.yaml --verbose**


Adding the contents of the directive file
--
module-version: 0.2.11
nested-object-to-string: true
subject-prefix: CV
directive:
  - from: OpenAPI3.yaml
    where: >-
      $.servers[0].url
    set: >-
       http://WebserverUrl.Commvault.com/webconsole/api/

  - from: OpenAPI3.yaml
    where: >-
      $.info.title
    set: >-
       CommvaultPowerShell
      
  - from : OpenAPI3.yaml
    where: >-
      $.paths..content
    transform: >-
      const json_obj = {};
      for(var each in $)
      {
        if(each != "application/xml")
        {
            json_obj[each] = $[each];
        }
      }
      return json_obj
  - where:
      variant: ^Create$|^CreateViaIdentity$|^Update$|^UpdateViaIdentity$
    remove: true


         




[OpenAPI3.txt](https://github.com/Azure/autorest.powershell/files/10224394/OpenAPI3.txt)

**Comment by dolauli** [comment]
If you want to pass false, you should use `-<switchname>:$false`.
And for an optional bool parameter, the mapping is as below.
`-<switchname>:$false` -> false
`-<switchname>` -> true
The switch parameter is not provided -> not appear in the payload.

**Comment by JnaneshD05** [comment]
This info worked . Thanks a lot for the help!

**Comment by Stinjy69** [comment]
I know this is old, but Microsoft's documentation for "Update-MgUser" is out of date here:

https://learn.microsoft.com/en-us/microsoft-365/enterprise/block-user-accounts-with-microsoft-365-powershell?view=o365-worldwide

Dolauli's comment resolved this correctly.
