### ISSUE TITLE
[Internal] Autorest.Powershell dotnet SDK generator known issues

### ISSUE THREAD

**Issue by VeryEarly** [Azure/autorest.powershell#1045]
- XXXOperationsExtensions.cs
  -  operation was casted to interface: 
  ```powershell: return ((ISnapshotsOperations)operations).ListAsync().GetAwaiter().GetResult()```
  ```csharp: return operations.ListAsync().GetAwaiter().GetResult();```

- XXXOperations.cs
  - some 'this.' were not trimmed
  ``` powershell: throw new ValidationException(ValidationRules.CannotBeNull, "Client.SubscriptionId");```
  ``` csharp: throw new ValidationException(ValidationRules.CannotBeNull, "this.Client.SubscriptionId");```

- IXXXOperations.cs
  - namespaces of exceptions in comment section were not trimmed, same cases in XXXOperations.cs were trimmed as expected
  ``` powershell: /// <exception cref="CloudException">```
  ``` chsarp: /// <exception cref="Microsoft.Rest.Azure.CloudException">```

**Comment by dolauli** [comment]
Resolved already.
