### ISSUE TITLE
Disallowed html tags in help docs

### ISSUE THREAD

**Issue by isra-fel** [Azure/autorest.powershell#1102]
## Description

[In some cases](https://github.com/Azure/azure-powershell/pull/20643), we will generate help documents like this:

```markdown
  - `[GalleryApplicationVersionName <String>]`: The name of the gallery Application Version to be created. Needs to follow semantic version name pattern: The allowed characters are digit and period. Digits must be within the range of a 32-bit integer. Format: <MajorVersion>.<MinorVersion>.<Patch>

### -Id
Role Definition Unique Id(Format is <databaseName>.<roleName>).
```

The `<MajorVersion>, <MinorVersion>, <Patch>, <databaseName>, <roleName>` are placeholders. But they are recognized as HTML tags (because of the `<>`). So the build of docs is affected.

## Possible solution
We can use a tool like https://www.npmjs.com/package/sanitize-markdown (not verified) and define an allowed list of HTML tags. When it detects any invalid HTML tag, we transforms it to another safe format.

Possible formats:
```
<Example> -> {Example}
<Example> -> `<Example>`
```

**Comment by BethanyZhou** [comment]
Close as tracking by https://github.com/Azure/autorest.powershell/issues/832
Angle brackets may be included in the interface information of notes section or parameter and command description.
- Interface information in notes section will be removed in v4 if PR#https://github.com/Azure/autorest.powershell/pull/1164  merged, tracking this issue by https://github.com/Azure/autorest.powershell/issues/832
- angle brackets in parameter and command description are escaped already as  ```<Example> ->\<Example>\```
See https://github.com/Azure/autorest.powershell/blob/a638a03496b72ea7053a3b09c60cab77b226aed2/powershell/resources/psruntime/BuildTime/Models/PsHelpMarkdownOutputs.cs#L174-L179
