### ISSUE TITLE
Files generated by "model-cmdlet" will no be removed after "model-cmdlet" is removed.

### ISSUE THREAD

**Issue by YanaXu** [Azure/autorest.powershell#1122]
In **directive** of "README.md", I add the following part: 
```markdown
  - model-cmdlet:
    - SqlVirtualMachine
```
After I run autorest and .\build-module.ps1, I find below files.
```powershell
PS  \SqlVirtualMachine> ls -Recurse New-AzSqlVirtualMachineObject* | Resolve-Path -Relative
.\custom\autogen-model-cmdlets\New-AzSqlVirtualMachineObject.ps1
.\docs\New-AzSqlVirtualMachineObject.md
.\examples\New-AzSqlVirtualMachineObject.md
.\exports\New-AzSqlVirtualMachineObject.ps1
.\test\New-AzSqlVirtualMachineObject.Tests.ps1
```

I remove the **model-cmdlet** part from "README.md", and run autorest & build-module.ps1 again.
These files are still there. It feels like the removal of "model-cmdlet" is not working.
If these files are untouched, they should be removed somehow.

**Comment by dolauli** [comment]
We need to  clean the custom\autogen-model-cmdlets folder when regenerating the module.

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/1128.
