### ISSUE TITLE
PSSwagger Replacement?

### ISSUE THREAD

**Issue by grock90** [Azure/autorest.powershell#113]
In discovering that PSSwagger is no longer supported, and has instead been replaced by AutoRest, is there any support for a PSSWagger like tooling?  Having auto-generated pscmdlets is great for the testing community.   Any information is greatly appreciated!

Keep hitting this error in PSSwagger which lead me to discover it was moved to Autorest. 

error CS1503: Argument 1: cannot
convert from 'System.Net.Http.HttpClient' to 'System.Net.Http.DelegatingHandler'

**Comment by dolauli** [comment]
Close the issue, since it has nothing to do with autorest.powershell.
