### ISSUE TITLE
Simplify only one property class conflict with polymorphism

### ISSUE THREAD

**Issue by wyunchi-ms** [Azure/autorest.powershell#1144]
Autorest.PowerShell will simplify the output to the child class if the output type only have one property. But this will conflict when the output is a base class of polymorphism.

Such as: [SAPSizingRecommendationResult](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/workloads/resource-manager/Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2503). The output type will be `DeploymentType`

**Comment by dolauli** [comment]
The issue is duplicated with https://github.com/Azure/autorest.powershell/issues/952.
