### ISSUE TITLE
[Bug] Property should be public if it is a polymorphism type because its fields can't be expanded fully

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/autorest.powershell#1151]
https://github.com/Azure/azure-rest-api-specs/blob/fda03acb3594cdd152e50146045adcf588b8c6cf/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/bms.json#L8724

Workaround:
  - from: source-file-csharp
    where: $
    transform: $ = $.replace('internal Microsoft.Azure.PowerShell.Cmdlets.Kusto.Models.Api20221229.IDataConnection Property', 'public Microsoft.Azure.PowerShell.Cmdlets.Kusto.Models.Api20221229.IDataConnection Property');

**Comment by dolauli** [comment]
Fixed in autorest.powershell v4
