### ISSUE TITLE
[PowerShell][Request] Allow for retry on certain failures

### ISSUE THREAD

**Issue by deathly809** [Azure/autorest.powershell#119]
In AzureStack we have some operations on our operator side which can result in service migration.  During this migration the client might see an error which results in a broken connection.  For some operator operations we don't have a way to resume monitoring: update, repair node, etc.

We would like a way to provide customization so that if certain cmdlets see an exception it can wait some period of time and try again.  Currently, the C# SDK has [hard coded](https://github.com/Azure/azure-sdk-for-net/blob/306396c82f9349ff79f1a4ceb74bfbd1b5a0f470/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/LRO/LROPollState.cs#L207) a similar solution that allows them to handle specific error codes for older APIs.

Do you think it could be possible to expose a set of Funcs (Func<HttpResonseMessage, bool>) for each operations, POST, GET, DELETE, etc... where given a specific HttpResponseMessage it would return true when the client should retry, false when it should fail?

**Comment by deathly809** [comment]
@fearthecowboy This is for specific cmdlets I believe.  Usually related cmdlets which might cause a service to migrate to another node which would cause a blip and the cmdlet to fail.  I don't think it would hurt to add it for an entire module though.  I will need to reach out to the team that asked for this, we had a re-org and I need to find out who owns this now.

**Comment by fearthecowboy** [comment]
Hopefully it's ok for all, if its not, I'm pretty sure I _can_ give you another alternative that tweaks the pipeline on a per-cmdlet basis; the only downside is that you'd have to implement tiny partial class for each one.

It's also possible I could craft a directive you could use. 

G

**Comment by deathly809** [comment]
@fearthecowboy  I can't imagine anything bad can happen.  But, that is how bugs happen I guess lol.  

Too bad we can provide a class that allows us to Inherit from your class where we can define a method that you call after you add all the default handlers i.e

```
public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> FinalHandler( System.Net.Http.HttpRequestMessage requestMessage, Runtime.IEventListener listener, Runtime.ISendAsync next );
```

**Comment by fearthecowboy** [comment]
That's actually not too hard to implement -- generated cmdlets only inherit from  `PSCmdlet` -- we don't force a weird base class.

Would be a small directive to alter the inheritance on a subset of cmdlets so you could make a class inherit from PSCmdlet and the generated cmdlets could inherit from that.

I was thinking of that ; just want to see if a `partial` method in a child class can be fulfilled by a base class.

**Comment by deathly809** [comment]
@fearthecowboy What would the tag thing entail?  Could we provide something in the spec itself?  Something like x-ms-failover-aware?
