### ISSUE TITLE
Parent/child pipeline invocation threw exception

### ISSUE THREAD

**Issue by vidai-msft** [Azure/autorest.powershell#1198]
When running the command `Get-AzElasticMonitor -ResourceGroupName ElasticResourceGroup01 -Name Monitor01 | Get-AzElasticAllTrafficFilter`, it threw exception `Get-AzElasticAllTrafficFilter_ListViaIdentityMonitor: Invalid identity for URI '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Elastic/monitors/{monitorName}'`. The README.md is located at https://github.com/vidai-msft/azure-powershell/blob/elastic-api-version-upgrade/src/Elastic/README.md

**Comment by dolauli** [comment]
@VeryEarly Please check whether it is an issue related to parent pipeline

**Comment by VeryEarly** [comment]
fixed
