### ISSUE TITLE
Cannot control switching between table and list views

### ISSUE THREAD

**Issue by lijinpei2008** [Azure/autorest.powershell#1201]
Switch controller `auto-switch-view: false` fails: https://github.com/Azure/autorest.powershell/blob/main/docs/features-of-v4.md#switch-between-table-view-and-list-view-based-on-result-number

Source code: https://github.com/Azure/azure-powershell/tree/feature/spring-autogen-v4/src/Spring

![image](https://github.com/Azure/autorest.powershell/assets/31384087/e205f3dd-4631-44cc-a63d-deceadd7482f)
![image](https://github.com/Azure/autorest.powershell/assets/31384087/d955cd2c-8cb6-416c-8fe4-e564325ddb78)

**Comment by dolauli** [comment]
@BethanyZhou It seems a bug. Please take a look.
