### ISSUE TITLE
Problems caused by upgrading modelerfour

### ISSUE THREAD

**Issue by lijinpei2008** [Azure/autorest.powershell#1205]
V3 was able to generate the command successfully, V4 had an error when executing autorest
![image](https://github.com/Azure/autorest.powershell/assets/31384087/2d216858-9530-44cd-b266-c9ce9e7dd421)

swagger file used when error occurs: https://github.com/Azure/azure-rest-api-specs/blob/288939a1c67efd5f129124ea0912ca17ff7b9d90/specification/eventgrid/resource-manager/Microsoft.EventGrid/stable/2022-06-15/EventGrid.json
![image](https://github.com/Azure/autorest.powershell/assets/31384087/cc1ba4ab-fc7a-4f3d-9922-6159f9c19ac2)

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/1206
