### ISSUE TITLE
Set the ConfirmImpact of New-Az*Object and Get-* to Low rather than using default value

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/autorest.powershell#1226]
Our static analyzer always reports New-Az*Object has signature issue and developer has to suppress them by configuring our tools.

To save engineer effort, please exempt New-Az*Object from "should implement ShouldProcess" issue.

```
"Az.NetworkCloud","New-AzNetworkCloudEndpointDependencyObject","New-AzNetworkCloudEndpointDependencyObject","1","8100","New-AzNetworkCloudEndpointDependencyObject Does not support ShouldProcess but the cmdlet verb New indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"

```

For Get-* cmdlet, its ConfirmImpact is empty. PowerShell will use  "High" as its ConfirmImpact by default if not specify. And our static analyzer reports "the cmdlet should implement ShouldProcess" warning.

```
"Az.NetworkCloud","Get-AzNetworkCloudAgentPool","Get-AzNetworkCloudAgentPool","2","8010","Get-AzNetworkCloudAgentPool Changes the ConfirmImpact but does not set the SupportsShouldProcess property to true in the cmdlet attribute.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"
```

**Comment by dolauli** [comment]
New-Az*Object is a client side cmdlet to create an object. So both new-Az*object and Get-* will not change any thing in service side, so adding **shouldprocess** with even **confirmImpact** set to **low** does not make sense here.
I think we should fix the analyzer instead.

**Comment by BethanyZhou** [comment]
Close as add task to improve static analyzer for these two kinds of cmdlets.
