### ISSUE TITLE
Dependency to Azure Commands.Utilities.Common in generated powershell CLI

### ISSUE THREAD

**Issue by siadatism** [Azure/autorest.powershell#1251]
Hi, I used **autorest** in Linux (Ubuntu 20.04) to create a Powershell CLI for a RestAPI of a web app of mine. Generating and building went successfully (after some tries and fixes). But when I run the generated command I get this error:

    InvalidOperation: /root/BSN.IpTables.Cli/generated/exports/ProxyCmdletDefinitions.ps1:276
    Line |
     276 |  … ommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS …
         |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         | Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].

It seems generated powershell script wants to use an Azure utility cmdlet but it can't find it. I tried to install Azure powershell packages but the error persists. Also, I commented corresponding lines in the mentioned script of the error, but the error is not fixed.

How can I fix this error and run the generated CLI?

Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

**Comment by dolauli** [comment]
@BethanyZhou Seems a similar issue to https://github.com/Azure/autorest.powershell/issues/1250. Azure logic is added in non-azure autogen.
