### ISSUE TITLE
Create connect function

### ISSUE THREAD

**Issue by siadatism** [Azure/autorest.powershell#1252]
I used Autorest to create a Powershell CLI for my Rest API using its swagger. I want to have a connect function to get the server address (host) and save it for later commands like an open session. It's nice to check the server availability in the connect function as well.

Is there anything like this in the generated CLI? If not, how can I add this functionality to it? Thanks.

**Comment by soroshsabz** [comment]
ITNOA

@dolauli I have the same problem, Did you can provide solution for this?

**Comment by soroshsabz** [comment]
I ask this question on SO 

https://stackoverflow.com/q/77297750/1539100

**Comment by dolauli** [comment]
@siadatism You do not need to do that, since we have created a shared httpclient in a file like https://github.com/Azure/azure-powershell/blob/main/src/Databricks/generated/Module.cs. Besides I do not think you will need to check server availability, since it is rare case and the check will take some additional cost, even if the server/service is not avail and we do not have the check, the request will also fail and an error will be reported to users.

**Comment by soroshsabz** [comment]
@dolauli So, how to specify URL when I call cmdlet?

For example I have a CLI for some services that host on appliance, so when I want to call CLI, I want to specify which appliance, must be response to me.

**Comment by dolauli** [comment]
You may use https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-parameterized-host in your swagger, by doing that, we could generate host for you to input for each cmdlet.
Or, you may set a placeholder in swagger. And then add a handler in our pipeline through customization to replace the host with the real host (set in env variable or a file). [Here ](https://github.com/Azure/azure-powershell/blob/main/src/Resources/MSGraph.Autorest/custom/CSharp/Module.cs)is an example how to add a handler.

**Comment by soroshsabz** [comment]
related to https://github.com/BSVN/IpTables.Api/pull/22

**Comment by soroshsabz** [comment]
> You may use https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-parameterized-host in your swagger, by doing that, we could generate host for you to input for each cmdlet. Or, you may set a placeholder in swagger. And then add a handler in our pipeline through customization to replace the host with the real host (set in env variable or a file). [Here ](https://github.com/Azure/azure-powershell/blob/main/src/Resources/MSGraph.Autorest/custom/CSharp/Module.cs)is an example how to add a handler.

@dolauli So How Azure implement `Connect-AzAccount`?

thanks a lot for helping me :)

**Comment by soroshsabz** [comment]
@dolauli Did you can get me more advice to implementing clean code `Connect-AzAccount` like cmdlet?

thanks

**Comment by soroshsabz** [comment]
I ask some question about this

https://github.com/Azure/azure-powershell/discussions/23233

**Comment by soroshsabz** [comment]
We can done it, thanks to @dolauli  .

All developers can see our example in: https://github.com/BSVN/IpTables.Api/pull/56
