### ISSUE TITLE
Need a way to sleep in the test script

### ISSUE THREAD

**Issue by wyunchi-ms** [Azure/autorest.powershell#1279]
Current if we want to sleep in the `Recprd` mode, we need call `Start-Sleep` in the test script. But this will also sleep that long in the `Playback` mode. Find a way to run mocked `sleep` in `Playback` mode will save about 40 mins for our full autorest test..

**Comment by isra-fel** [comment]
Short term: create a Start-TestSleep that can skip sleeping in playback mode to replace Start-Sleep. Ref: https://github.com/Azure/azure-powershell/blob/main/tools/TestFx/Common.ps1#L643

Long term: add a linting rule to detect Start-Sleep in test cases.

**Comment by dolauli** [comment]
@vidai-msft Please close the issue if it has been implemented.

**Comment by vidai-msft** [comment]
Issue resolved by PRs [#23625] and [#23650]
