### ISSUE TITLE
Test-Module: Import Az.Accounts should not be required 

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#1313]
if azure: false in metadata, import of Az.Accounts should not be required during testing.
https://github.com/Azure/autorest.powershell/blob/b9d6f405cc4370634b916543e97ea7fb84ae0063/powershell/resources/assets/test-module.ps1#L32
a simple comment this line if azure: false 

Resources isnt really needed either but doesnt stop testing.

**Comment by dolauli** [comment]
If azure:false, Az.Accounts will not be imported actually.

**Comment by dicolanl** [comment]
@dolauli  see screen shots, azure = false, but still tries to import az.accounts.

<img width="1512" alt="image" src="https://github.com/Azure/autorest.powershell/assets/25964057/04572562-66e2-4204-b484-290424a3836b">

<img width="1512" alt="image" src="https://github.com/Azure/autorest.powershell/assets/25964057/79490070-9c10-492a-b1f8-124cd7836ef3">
