### ISSUE TITLE
format url is invalid type when generating with autorest 3.x

### ISSUE THREAD

**Issue by JoyerJin** [Azure/autorest.powershell#1343]
Run cmdlet:

autorest --azure --input-file:https://github.com/Azure/azure-rest-api-specs/blob/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/machineLearningServices.json --use:@autorest/powershell@3.x

Error:

at State.getValue (---\.autorest\@autorest_powershell@3.0.519\node_modules\@autorest\powershell\utils\model-state.ts:69:13)
(node:30576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1812)
fatal   | Error: Unknown Model. Fatal.
error   | UnknownJsonType/LLCS2000 | **Schema 'WorkspaceConnectionOAuth2AuthUrl' is declared with invalid type 'uri'**
fatal   | Error: Unknown Model. Fatal.
fatal   | Process() cancelled due to failure
error   |   Error: Plugin llcsharp-v2 reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.

Swagger:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/machineLearningServices.json#L7177

**Comment by isra-fel** [comment]
@dolauli to provide workaround. We won't fix this in v3.

**Comment by dolauli** [comment]
To workaround the issue in v3, we could remove `"format": "url"` from swagger through a directive. Specific for this case, the directive should be as following:
```
  - from: swagger-document
    where: $.definitions.WorkspaceConnectionOAuth2.properties.authUrl
    transform: delete $.format
```
