### ISSUE TITLE
Add support for 'operation-location' for dataplane LRO(Long Running Operations)

### ISSUE THREAD

**Issue by v-vprasannak** [Azure/autorest.powershell#1344]
Please add support for dataplane LRO, response headers 'operation-location'.

**Comment by dolauli** [comment]
[Official docs](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#patterns-to-initiate-a-long-running-operation) for using `operation-location` in dataplane.

**Comment by isra-fel** [comment]
Currently blocking Communication team
