### ISSUE TITLE
MG-graph Mail Forward issue

### ISSUE THREAD

**Issue by ybar17** [Azure/autorest.powershell#1349]
Hi, 
Because Microsoft deprecated the PowerShell Exchange-Online command, 
I rewrite my script to MG-graph, 
I got no errors, but it did not affect the user.
The code is attached 
[Mail forwarding.txt](https://github.com/user-attachments/files/16095010/Mail.forwarding.txt)

**Comment by dolauli** [comment]
Hi @ybar17, It seems you created the issue in the wrong repo. The repo is for the tool to generate PowerShell modules based on swagger.
