### ISSUE TITLE
Module fails to build due to missing arguments

### ISSUE THREAD

**Issue by dsolodow** [Azure/autorest.powershell#1353]
Using the Swagger for Dayforce HCM, Ubuntu 22.04, pwsh 7.4, dotnet-sdk 8
On the first pass of autorest, it gives a couple of errors:
![image](https://github.com/Azure/autorest.powershell/assets/7574074/e1ca83bf-5e12-42c4-a8b1-b2712e654af2)

If I add the following to the yaml block in the readme.md:
```yaml
directive:
- no-inline:
  - AmfRuleParameterModel
```
it will generate the files, but the build fails with a slew of "error CS0839: Argument missing":
![image](https://github.com/Azure/autorest.powershell/assets/7574074/900a2a49-b239-4c54-b8c8-c0cc38f29e74)

**Comment by dolauli** [comment]
@dsolodow Would you provide swagger and more details about how you generate the modules?

**Comment by dolauli** [comment]
autorest can not support response as below.
<img width="805" alt="image" src="https://github.com/user-attachments/assets/64505505-ea86-454a-933c-057d4c96ee9d">

**Comment by dsolodow** [comment]
Thanks; what if anything can be done to work around or resolve?

**Comment by dolauli** [comment]
Is that a real case that API does not response a json but xml?

**Comment by isra-fel** [comment]
We don't have a plan to support xml response (or anything other than json).
@dolauli let's put this in the README.md

**Comment by dsolodow** [comment]
> We don't have a plan to support xml response (or anything other than json). @dolauli let's put this in the README.md

So the ones that look to support multiple return types will be an issue as well?

```json
"responses": {
          "204": {
            "description": "The KPI Data has been updated",
            "content": {
              "application/json": { },
              "text/json": { },
              "text/html": { }
            }
          },
```

**Comment by dolauli** [comment]
If there is "application/json" response, it should be supported. Otherwise, Please file a bug in the [autorest repo](https://github.com/Azure/autorest).
