### ISSUE TITLE
Miscellaneous Issues For Later

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#149]
- [ ]  Default Parameter Set from config
- [ ]  Default Parameter Value (x-ms-default)
- [ ]  Configurable Force 
- [ ]  Parameter Position
   - [ ] from configuration
   - [ ] default pattern
- [ ] documentation on OAI level directives

**Comment by MiYanni** [comment]
Closing as these are covered by other issues
