### ISSUE TITLE
Optional Enum with Single value?

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest.powershell#158]
A parameter that is an `enum` that has a single value should be implemented as a switch parameter.

**Comment by fearthecowboy** [comment]
This can be done in the cmdlet class generator, add a check to see if there is a single value in the enum and switch to generating a switch.

``` 
foo: 
  type: string
  enum: ['system assigned'] 
```
when that is optional the only two states are add the value or nothing...

**Comment by dolauli** [comment]
We will not support this considering users may add more values to single value enum.
