### ISSUE TITLE
Arrays type creating wrong url endpoint

### ISSUE THREAD

**Issue by NakulSabharwal** [Azure/autorest.powershell#197]
On using the openapi-user-original.yml it generates the wrong url building code
```
var _url = new global::System.Uri((
                        "https://graph.microsoft.com/v1.0/me"
                        + "?"
                        + Select != null && Select.Length > 0 ? "Select=" + System.Uri.EscapeDataString(System.Linq.Enumerable.Aggregate(Select, (current, each) => current + "," + (string.IsNullOrEmpty(each) ? System.Uri.EscapeDataString(each) : System.String.Empty))) : System.String.Empty
                        ).TrimEnd('?','&'));
```
Run Invoke-MeUserGetUser -select "abc"
Expected url constructed = https://graph.microsoft.com/v1.0/me?select="abc"
Actual url constructed = select="abc"

**If I replace all the array type to string in the yml file as given in openapi-user-edited.yml file**
```
var _url = new global::System.Uri((
                        "https://graph.microsoft.com/v1.0/me"
                        + "?"
                        + (string.IsNullOrEmpty(Select) ? global::System.String.Empty : "$select=" + System.Uri.EscapeDataString(Select))
                        ).TrimEnd('?','&'));
```
This constructs the expected url https://graph.microsoft.com/v1.0/me?select="abc" and calls the correct endpoint and gives response. 
[openapi.zip](https://github.com/Azure/autorest.powershell/files/3053465/openapi.zip)

**Comment by fearthecowboy** [comment]
Fixed in `autorest.powershell` @ `2.0.354`

**Comment by fearthecowboy** [comment]
use `autorest --reset` to update the plugins.
