### ISSUE TITLE
Release Notes for pre-beta

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest.powershell#20]
# BEFORE YOU BEGIN: IMPORTANT NOTES
There are a *lot* of what I consider to be "minor" issues in here. My priority at this point has been to get enough generated code in place to get the complete end-to-end scenarios functioning, and I can worry about the 'details' once we start thoroughly testing. 

Modifing the generation is actually really really trivial for me, so I consider the vast majority of the rest of it 'pretty minor'

I have code that's not exposed where auth and other things are handled for generating support for Azure ARM resources, and that's not going help you.

## If this doesn't work for for you
Don't panic; this is pre-beta, and it works great for certain scenarios, but they may not be yours

## If you can't get it to work with your stuff
Wait till I get back from vacation. I can't really help before I get back.

## If you try to use petstore.json for testing
You will be smacked with a newspaper, and I shall not give you a treat.

## If you don't think the cmdlets are very good
I should remind you that Jeffrey Snover reviewed this and he thinks a bit different.  You will have to wait till I get back for me to document why this works the way it does. Trust me when I say, I went to great lengths to design things a certain way, and *everything* has purpose and reason.

# Caveats and known issues: 

## PLEASE IGNORE the errors like:

(they are actually harmless)

``` yaml
Error occurred in handler for 'ReadFile' in session 'session_5':
Error: Could not read 'obj/test.txt'.
    at QuickDataSource.ReadStrict (C:\Users\garretts\.autorest\@microsoft.azure_autorest-core@2.0.4280\node_modules\@microsoft.azure\autorest-core\dist\lib\data-store\data-store.js:26:19)
    at <anonymous>
Error occurred in handler for 'ReadFile' in session 'session_7':
Error: Could not read 'ContainerRegistryManagement.private.csproj'.
    at QuickDataSource.ReadStrict (C:\Users\garretts\.autorest\@microsoft.azure_autorest-core@2.0.4280\node_modules\@microsoft.azure\autorest-core\dist\lib\data-store\data-store.js:26:19)
    at <anonymous>
```

## Bugs
- there are a lot of little bugs. I haven't published my backlog yet.

## WHAT IS MISSING FROM THIS BUILD
- auth support 
- documentation and explinations. 
- field/class/property/method descriptions. Some are there, but I gotta go thru and do good pass everywhere.
- Handlers for Retry/etc --
- Persisting/editing names/parameters/etc for generated commands
- use of proxy settings/etc
- no support for streams, duration, or arrays at the root/base level of the request/response

# Getting Started

## Requires:

- node 8.11.3 (stay away from node 10 for now<br>
https://nodejs.org/dist/v8.11.3/node-v8.11.3-x64.msi

- autorest 2.0.4280+ <br> 
`npm install -g autorest`

- dotnet 2.0.0 sdk - either install the one from the .net page or use 
<br>
`npm install -g dotnet-sdk-2.0.0`

- powershell core 6<br>
https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/PowerShell-6.0.2-win-x64.zip

- install the autorest.incubator plugin :<br>
`autorest --reset`<br>
`autorest "--use=@microsoft.azure/autorest.incubator@preview" `<br>

## Usage
`autorest  --use="@microsoft.azure/autorest.incubator@preview" --powershell --output-folder=`*output-folder* `--input-file=`*path-or-url-to-swagger-file* 

## sample run:
``` powershell
# run these from powershell core. 
# Windows Powershell is not ok. 
# The cmdlets can work in both, but be patient
 
autorest --use="@microsoft.azure/autorest.incubator@preview" --powershell --input-file=https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2018-03-01/redis.json
--output-folder=./generated

# will generate the cmdlets into the output-folder
cd ./generated

# now we do one last step (build proxies and import the module)
./generate-proxies.ps1 -test

# Now you're in a new pwsh instance with the cmdlets
#example: 
get-operation -verbose -debug 
```

**Comment by JonKohler** [comment]
One quick comment - we're working through this - small typo on npm install, should be - npm i -g dotnet-sdk-2.0.0 not npm i -g dotnet-sdk.2.0.0

**Comment by mallochine** [comment]
```
$ sudo npm install -g dotnet-sdk.2.0.0
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens
or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: dotnet-sdk.2.0.0@latest
```

don't think it works on centos7

**Comment by mallochine** [comment]
Trying the powershell autorest generation code here: https://github.com/Azure/autorest/tree/master/Samples/1a-code-generation-minimal

```
$ autorest --use="@microsoft.azure/autorest.incubator@preview" --powershell
AutoRest code generation utility [version: 2.0.4280; node: v10.5.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (2.0.4282).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      '/Users/alex.guo/.autorest/@microsoft.azure_autorest-core@2.0.4280/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4280)
   Loading AutoRest extension '@microsoft.azure/autorest.incubator' (preview->1.0.86)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.67)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.50->2.3.50)

WARNING (UndefinedTypeWithSchema): The schema 'User' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - swagger-document:1:0

WARNING (UndefinedTypeWithSchema): The schema 'Category' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - swagger-document:1:0

WARNING (UndefinedTypeWithSchema): The schema 'Pet' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - swagger-document:1:0

WARNING (UndefinedTypeWithSchema): The schema 'Tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - swagger-document:1:0

WARNING (UndefinedTypeWithSchema): The schema 'Order' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - swagger-document:1:0

WARNING (TypeFileNotValid): The schema type 'file' is not a OAI standard type. This has been auto-corrected to 'type:string' and 'format:binary'
    - swagger-document:1:0
Error: Format 'Binary' not implemented.
    at SchemaDefinitionResolver.resolveTypeDeclaration (/Users/alex.guo/.autorest/@microsoft.azure_autorest.incubator@1.0.86/node_modules/@microsoft.azure/autorest.incubator/src/csharp/schema/schema-resolver.ts:80:19)
    at nameStuffRight (/Users/alex.guo/.autorest/@microsoft.azure_autorest.incubator@1.0.86/node_modules/@microsoft.azure/autorest.incubator/src/csharp/namer.ts:146:49)
Error: Inputs missing.
    at process (/Users/alex.guo/.autorest/@microsoft.azure_autorest.incubator@1.0.86/node_modules/@microsoft.azure/autorest.incubator/src/csharp/lowlevel-generator/main.ts:20:13)
Error: Inputs missing.
    at Object.processCodeModel (/Users/alex.guo/.autorest/@microsoft.azure_autorest.incubator@1.0.86/node_modules/@microsoft.azure/autorest.incubator/src/common/process-code-model.ts:18:13)
Error: Inputs missing.
    at processRequest (/Users/alex.guo/.autorest/@microsoft.azure_autorest.incubator@1.0.86/node_modules/@microsoft.azure/autorest.incubator/src/powershell/powershell-generator.ts:17:13)
```

**Comment by JonKohler** [comment]
And yes, we realize that test with petstore is a slap on the nose, but given we were having some challenges, we decided to start with the basics as a sanity check

**Comment by fearthecowboy** [comment]
@mallochine : "no support for **streams**, duration, or arrays at the root/base level of the request/response"

**Comment by mallochine** [comment]
I'm not that familiar with the petstore example (linked in 1a-code-generation-minimal). What is a stream exactly? Is it where 'readme.md' is read into stdin? Should I actually have done --input-file="a.json" or something similar?

If yes to that last question, then I actually still run into the same code generation problem. So, please elaborate on what is a 'stream'?

**Comment by fearthecowboy** [comment]
No; the swagger file has `format: binary` somewhere in it.

That ends up being a stream. Not yet supported.

**Comment by JonKohler** [comment]
Ahha! We've got those all over the place in our code, which means a nice "e brake" for us here :(

Are you back from PTO @fearthecowboy ? Or more apt question - is there another drop that might support binary in the works?

Does it make sense for us to dig into the code and submit a PR, or just leave you too it at this point? No rush, we want to help you out here as much as we can, as i strongly believe that AutoRest is going to be our true north for both traditional client binaries (for other languages) and PowerShell (from the sounds of it)

**Comment by deathly809** [comment]
Spacing between comments and previous code would be great,

```csharp
        /// <summary>The URI for the proxy server to use</summary>
        [System.Management.Automation.Parameter(Mandatory = false, DontShow= true, HelpMessage = "The URI for the proxy server to use")]
        public System.Uri Proxy {get;set;}
        /// <summary>Credentials for a proxy server to use for the remote call</summary>
        [System.Management.Automation.Parameter(Mandatory = false, DontShow= true, HelpMessage = "Credentials for a proxy server to use for the remote call")]
        [System.Management.Automation.ValidateNotNull]
        public System.Management.Automation.PSCredential ProxyCredential {get;set;}
```

to

```csharp
        /// <summary>The URI for the proxy server to use</summary>
        [System.Management.Automation.Parameter(Mandatory = false, DontShow= true, HelpMessage = "The URI for the proxy server to use")]
        public System.Uri Proxy {get;set;}

        /// <summary>Credentials for a proxy server to use for the remote call</summary>
        [System.Management.Automation.Parameter(Mandatory = false, DontShow= true, HelpMessage = "Credentials for a proxy server to use for the remote call")]
        [System.Management.Automation.ValidateNotNull]
        public System.Management.Automation.PSCredential ProxyCredential {get;set;}
```

**Comment by fearthecowboy** [comment]
Yes. Agreed. that's been driving me crazy.

**Comment by JonKohler** [comment]
For the ItemGroup > PackageReferences - what are your thoughts about adding Rosyln analyzers in there? When we were handcrafting our cmdlets, we found that using the in-built dotnet analyzers did help give us a wee bit of sanity right on build. Before we did that, we ended up chasing half working code in some areas, that various "stuff" caught. I'm happy to send in a PR if you'd like with my ideas @fearthecowboy 

I'm talking about this part here: https://github.com/Azure/autorest.incubator/blob/a86ff8df11778f385e41243d90e7169ebe6e3347/src/powershell/powershell-generator.ts#L79

**Comment by fearthecowboy** [comment]
Yeah; we should have it conditional based on a configuration setting. 

ie, add one of these: https://github.com/Azure/autorest.incubator/blob/a86ff8df11778f385e41243d90e7169ebe6e3347/src/powershell/project.ts#L304 

``` typescript
this.enableRoslynAnalyzer = await service.GetValue('enable-roslyn-analyzer') || false;
```

and then emit it when `project.enableRoslynAnalyzer` is set. 

(trying to get things more configuration driven)

**Comment by JonKohler** [comment]
ok, I'll give it a crack if I can break away a few cycles over the next few days. That seems like a sane approach. 

The only tricky-ish bit is that we're statically creating the csproj by basically echo'ing a static config into a file with .writefile at the moment, which itself is fine.

Do we need to change that to be more like the bit right below it in code (the psd1 bit), where it has some conditional logic?

I could change it over to be this in the PR, but wanted to get your thoughts first

https://github.com/Azure/autorest.incubator/blob/a86ff8df11778f385e41243d90e7169ebe6e3347/src/powershell/powershell-generator.ts#L108

**Comment by fearthecowboy** [comment]
Yeah, it'd probably a good idea to move to the text-emitter style; it makes it easy to exclude stuff.
