### ISSUE TITLE
Logic for parsing operationIds needs to look past first word in verb

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#204]
When generating cmdlets from [this configuration file](https://github.com/Azure/azure-powershell/blob/generation/src/Resources/readme.md), there is an issue where cmdlets are duplicated with different names due to the naming of the operationIds.

For example, the following cmdlets are generated from the above configuration file:

- `Export-AzDeploymentTemplate` and `Export-AzDeploymentTemplateAtSubscriptionScope`
- `Test-AzDeploymentExistence` and `Test-AzDeploymentExistenceAtSubscriptionScope`

This issue occurred in more of the cmdlets, but a fix from @MiYanni and @NelsonDaniel to include "at" into the existing operation group filter ("by" and "with") resolved the issues in those cmdlets, but it still persists in these two cases. From offline discussions, it seems that this is due to the logic parsing the operationIds by looking for these filter words only after the first word in the verb, nothing more.

For the above cases, you can find the corresponding operationIds here:

- [`Deployments_ExportTemplateAtSubscriptionScope`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2018-05-01/resources.json#L303)
- [`Deployments_CheckExistenceAtSubscriptionScope`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2018-05-01/resources.json#L102)

In both cases, "At" comes after the second word in the verb, not the first, which we believe is causing this issue.

**Comment by fearthecowboy** [comment]
DONE.

**Comment by cormacpayne** [comment]
![Alt Text](https://media.giphy.com/media/WIg8P0VNpgH8Q/giphy.gif)
