### ISSUE TITLE
Upper case known 2 letter acronyms (all names)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#207]
In PowerShell/.NET, 2 letter acronyms are all uppercase. Meaning,
Instead of: `IpAddress`
Should be: `IPAddress`

This does not apply to abbreviations. Meaning,
This remains: `AccountId`
(*Side note: Az is an abbreviation*)

This applies to ALL names: cmdlets, parameters, classes, namespaces, properties, etc.

- Determine a list of 2 letter acronyms
  - Scan (via script) cmdlet/parameter/models/properties that have 2 letters, and manually determine which are acronyms
- Upper case the 2 letter acronyms early in code generation

**Comment by fearthecowboy** [comment]
Partial Fix: currently `MS`, `OS`, `VM` and 'IP'  are whitelisted for upcasing
