### ISSUE TITLE
Incorrect names of cmdlets generated

### ISSUE THREAD

**Issue by NakulSabharwal** [Azure/autorest.powershell#211]
The names of Cmdlets is being generated as **Get-** and **Update-** whereas expected cmdlets should be **Get-meUser** and **Update-meUser**. 
` PartialGraphApi                     {Get-, New-MicrosoftGraphUserObject, Update-}`

AutoRest code generation utility [version: 3.0.5173; node: v10.15.3]

[openapi-user.zip](https://github.com/Azure/autorest.powershell/files/3074287/openapi-user.zip)

**Comment by fearthecowboy** [comment]
The `operationId`  that you're using doesn't conform to the traditional azure guidelines.

historically, we've used a format of `[GROUP]_[OPERATION]` 

for example:
`operationId: me.user.GetUser` would be specified as `operationId: MeUser_Get`
`operationId: me.user.UpdateUser` would be specified as `operationId: MeUser_Update` 

What you have is getting parsed into 

`me.user.GetUser` 
> no underscore, so assume `group = ''`
> next, we split the words 
=> `me user get user`
> and search for an english verb
=> `action = 'get'`
> and then since there is text before and after, we assume the subject is immediately after 
=> `subject` = `user`
> and then the stuff before is discarded.

if you switch to 
`operationId: me.user.get` and `operationId: me.user.update` then it will assume the words before is the subject, and you'll get :
`Get-MeUser` and `Update-MeUser`
