### ISSUE TITLE
Extra variants generated with the same set of parameters for Get-AzEntity

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#212]
Using the following specs results in the generation of a large number of variants for `Get-AzEntity`, all of which have the same set of parameters:

- [`readme.md`](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/multiapi/specification/managementgroups/resource-manager/readme.md)
- [`readme.enable-multi-api.md`](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/multiapi/specification/managementgroups/resource-manager/readme.enable-multi-api.md)

Here is the corresponding API call in the spec for entities:

- [`/providers/Microsoft.Management/getEntities`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json#L418)

**Comment by fearthecowboy** [comment]
Apparently a docs issue. 

(discuss!)

**Comment by cormacpayne** [comment]
Fixed!

![Alt Text](https://media.giphy.com/media/WIg8P0VNpgH8Q/giphy.gif)
