### ISSUE TITLE
x-ms-parameterized-host support?

### ISSUE THREAD

**Issue by JustinGrote** [Azure/autorest.powershell#216]
In multitenant situations you may need to specify the account host as a parameter. Does/Will the powershell generator support x-ms-parameterized-host?

**Comment by JustinGrote** [comment]
1 month bump, any update or response?

**Comment by fearthecowboy** [comment]
Ah, sorry for the lack of response... It's been implemented

**Comment by JustinGrote** [comment]
No worries, I know you've been slamming hard on this and it shows. Thanks!
