### ISSUE TITLE
There no way to get actual error line

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/autorest.powershell#221]
Hello
How can I get actual error line of the Swagger input file? Right now the error message is really useless:

> PLUGIN FAILURE: Missing operation id?, Error: Missing operation id?

The same files correctly handled by NSwag.

**Comment by fearthecowboy** [comment]
You need `operationId` fields on all the operations in order for AutoRest to infer an appropriate name for the cmdlet.

(better errors are coming soon)

**Comment by antonGritsenko** [comment]
@fearthecowboy sure, I know that, same for NSwag. But as I already wrote, it works in NSwag, so all operationIds are set correctly (and I've double checked this with PowerShell script).
Sorry, I can't share publicly the Swagger definition of our API.

**Comment by dolauli** [comment]
Closed since no further update from the reporter for a long time
