### ISSUE TITLE
Need hook to provide Default URI and token audience for data plane cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#225]
For data plane cmdlets, Register-AzModule needs some hook from the generated code to specify the host from the Swagger, or some other indicator that a different Uri and Token Audience are required for the cmdlet.

Right now the base Host and Port come from a call to GetParameterValues - this call needs to include information about the host specified in Swagger, so we can determine which endpoint it is, and the corresponding audience value and endpoint value within the current azure environment.

For example, a host of vault.azure.net would indicate that the corresponding call is a call to the keyvault data plane, so GetParameterValues would look up the correct host and port from the currently selected environment.

Note that, if host is not an acceptable indicator, we could invent a new property, like x-ms-endpoint-name to provide this information.

**Comment by markcowl** [comment]
Per discussion - the appropriate thing here is to provide the host value from Swagger, and the GetParameterValues function will use this value to look up the appropriate value in the current environment.

**Comment by fearthecowboy** [comment]
We think this can be solved by updating the AzAccounts module: 

``` csharp
case Events.URLCreated:
 {
    var request = EventDataConverter.ConvertFrom(getEventData())?.RequestMessage as HttpRequestMessage;
    if (request != null)
    {
        // current target: 
        var host = request.RequestUri.Host;
        var port = request.RequestUri.Port;

        // anything else do we need to know to decide the target host/port?
        // 
        // set host and port according to the actual target 
        request.RequestUri = new UriBuilder(request.RequestUri) 
        {
          Host = host,
          Port = port
        }.Uri;
    }
 } 
 break;
```
