### ISSUE TITLE
ProtectFiles doesn't protect all files all the time?

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#271]
Make a file in custom or resources folder. Just make like, "New Text Document.txt". Regenerate an Azure PowerShell cmdlet. The file will disappear.

I've been having this happen frequently with making customizations. I have a 'latest' folder in custom and the entire folder just disappears. All files (and subdirectories) should be protected when that folder is declared as a protected folder.

**Comment by fearthecowboy** [comment]
resolved in autorest-core 3.0.5199+ and autorest-powershell 2.0.440+
