### ISSUE TITLE
Parameter from path result in compilation error if of type integer

### ISSUE THREAD

**Issue by Masus** [Azure/autorest.powershell#282]
Maybe I'm missing something but the following parameter definition in my swagger document will result in a compilation error when compiling the generated powershell module.

```
{
   "/api/v2/hardwareModel/{id}":{
      "get":{
         "tags":[
            "HardwareModel"
         ],
         "operationId":"HardwareModel_Get",
         "consumes":[

         ],
         "produces":[
            "application/json"
         ],
         "parameters":[
            {
               "name":"id",
               "in":"path",
               "description":"The Id of the model to fetch",
               "required":true,
               "type":"integer",
               "format":"int64"
            }
         ],
         "responses":{
            "200":{
               "description":"OK",
               "schema":{
                  "$ref":"#/definitions/HardwareModel"
               }
            }
         }
      }
   }
}
```
When compiling the generate .cs files the following error is generated:

> generated\cmdlets\GetHardwareModel_GetViaIdentity.cs(188,56): error CS1503: Argument 1: cannot convert from "\<null\>" to "long"

If the parameter is of type string everything compiles just fine.

**Comment by Masus** [comment]
Any thoughts around this? This issue is a blocker for us, if there are no plans to include this in the near future maybe I can help implement it. Will need some pointers for where to start though.

**Comment by fearthecowboy** [comment]
I think this is fixed in autorest.powershell 2.0.440. -- `autorest --reset` and try it now.

If not , add `--disable-via-identity` and it won't make those.

**Comment by Masus** [comment]
@fearthecowboy It does not seem to be fixed. Same error. I can work around this error by adding the flag you mentioned.

Encountered another compilation error which also has to do with non nullable parameters. Registering new issue for that.

**Comment by dolauli** [comment]
The issue has been fixed.
