### ISSUE TITLE
Error when building Graph cmdlets with latest changes

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#287]
When running `.\build-modules.ps1 -Docs` after generation using [this `readme.md`](https://gist.github.com/cormacpayne/9e80feea941148119a6df87bd3c3ecaf), I get a lot of errors similar to the following:

```
generated\cmdlets\AddAzADGroupMember_AddViaIdentity.cs(236,98): error CS1061: 'IResourcesIdentity' does not contain a definition for 'tenantId' and no accessible extension method 'tenantId' accepting a first argument of type 'IResourcesIdentity' could be found (are you missing a using directive or an assembly reference?) [C:\B\azure-powershell\src\Resources\Az.Resources.csproj]
```

For the above error, here is the corresponding line in `AddAzADGroupMember_AddViaIdentity.cs`:

```cs
await this.Client.GroupsAddMember(InputObject.GroupObjectId, InputObject.tenantId, Parameter, onNoContent, on, this, Pipeline);
```

In the `ResourcesIdentity.cs` file, the following property is defined:

```cs
public string TenantId { get => this._tenantId; set => this._tenantId = value; }
```

**Comment by fearthecowboy** [comment]
@cormacpayne  - This is fixed in autorest.powershell 2.0.440. -- `autorest --reset` and try it now.

**Comment by cormacpayne** [comment]
Fix has been confirmed 🎉
