### ISSUE TITLE
KeyVault data plane cmdlets missing parameter for vault

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#292]
The [KeyVault data plane spec](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L8-L22) defines an `x-ms-parameterized-host` for the `vaultBaseUrl`, which is represented in the current KeyVault data plane cmdlets as the `-VaultName` parameter.

The generator should account for the `x-ms-parameterized-host` property to expose the parameters defined.

**Comment by fearthecowboy** [comment]
`x-ms-parameterized-host` support is now in autorest + autroest.powershell.
