### ISSUE TITLE
Body parameter not being flattend in KeyVault

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#293]
The [`UpdateKey`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L178) operation references [`KeyUpdateParameters`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4901-L4928) as one of its body parameters, which references [`KeyAttributes`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3857-L3877) as its `attribute` property, which contains an `allOf` for [`Attributes`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3686-L3718). For the generated `Update-AzKeyVaultKey` cmdlet, there is an `-Attributes` parameter, but it has not been flattened to include properties such as `NotBefore`, `Expires`, etc.

The [`UpdateSecret`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L1072) operation references [`SecretUpdateParameters`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4967-L4987) as one of its body parameters, which references [`SecretAttributes`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4099-L4119) as its `attribute` property, which contains an `allOf` for [`Attributes`](https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3686-L3718). For the generated `Update-AzKeyVaultSecret` cmdlet, there is not `-Attributes` parameter since it has been flattened to include `-AttributesNotBefore`, `-AttributesExpire`, etc.

**Comment by fearthecowboy** [comment]
I've made the inliner more aggressive (inlines optional models when all properties are optional) 

in autorest.powershell 2.0.455
