### ISSUE TITLE
Formatting Support

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#299]
- [x] **Default Behavior**

  - Only ID parameters, in reverse order, should be in table formats
- [x] **Configuration Support**
  - Should be able to address configuration of model properties
    - Turn table format inclusion on/off
    - Set table format order
    - Set property column name
  - Should be able to suppress generated format for specified model[s]
- [ ] **Customization Support**
- Second phase generator should pick up format.ps1xml files and automatically include in ‘FormatsToProcess’ in module manifest (Tracked: https://github.com/Azure/autorest.powershell/issues/338)

**Comment by NelsonDaniel** [comment]
Default Behavior fixed with: https://github.com/Azure/autorest.powershell/pull/325 and https://github.com/Azure/autorest.powershell/pull/337
Configuration Support fixed with: https://github.com/Azure/autorest.powershell/pull/337 and https://github.com/Azure/autorest.powershell/pull/325
