### ISSUE TITLE
Hangs while generating for large openapi file

### ISSUE THREAD

**Issue by NakulSabharwal** [Azure/autorest.powershell#305]
I am trying to generate using a large openapi file but autorest getting hanged.
I increased memory using $ENV:NODE_OPTIONS=’--max-old-space-size=16384’
and ran autorest --powershell --input-file:open.yml

[open.zip](https://github.com/Azure/autorest.powershell/files/3205058/open.zip)

**Comment by NakulSabharwal** [comment]
@fearthecowboy This looks similar to https://github.com/Azure/autorest.powershell/issues/208 but our issue is for a much larger openapi file. During earlier optimization the size autorest was able to process increased but didn't reach full file.

**Comment by fearthecowboy** [comment]
O_O HOW BIG IS THAT FILE?! 

Send it to me, and I'll take a look.

**Comment by NakulSabharwal** [comment]
@fearthecowboy I have attached in this issue above. Named open.zip

**Comment by NakulSabharwal** [comment]
@fearthecowboy Any update on this issue? This is a blocker for us.

**Comment by fearthecowboy** [comment]
I've refactored autorest-core a lot to significantly reduce the memory usage, and get a small increase in speed. (I'm running it right now against your file, we'll see how long it takes)

Update to the latest autorest core and try now. 
```
npm install -g autorest@beta
autorest --reset
```

**Comment by fearthecowboy** [comment]
It' s still going after 3.5 hours (it's still working!), you've officially got the biggest OpenAPI I've ever seen.

You're might to want to break this up, and generate in pieces, and test with that, and only generate the whole thing together when you want to produce a final build.

**Comment by NakulSabharwal** [comment]
@fearthecowboy Did you get the final build ? Or it never got completed which was my case ?
