### ISSUE TITLE
Parameter naming and ParameterSet issues in Update/Set cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#308]
In most Set and update cmdlets in generated compute code, There is an InputObjectParameter with Type `IComputeIdentity` and there is a separate Parameter `Parameter` which is the body parameter for the underlying object

### Set cmdlets
(For example `Set-AzVmss` has a parameter called `Parameter` of type IVirtualMachineScaleSet`

This is in parameter sets containing both RGName + Name, and the InputObject parameter set.  
``` powershell
    [Parameter(ParameterSetName='Update1', Mandatory, HelpMessage='The name of the resource group.')]
    [Parameter(ParameterSetName='UpdateExpanded1', Mandatory, HelpMessage='The name of the resource group.')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Category('Path')]
    [System.String]
    ${ResourceGroupName},

    [Parameter(ParameterSetName='Update1', Mandatory, HelpMessage='Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.')]
    [Parameter(ParameterSetName='UpdateExpanded1', Mandatory, HelpMessage='Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Category('Path')]
    [System.String]
    ${SubscriptionId},

    [Parameter(ParameterSetName='Update1', Mandatory, HelpMessage='The name of the VM scale set to create or update.')]
    [Parameter(ParameterSetName='UpdateExpanded1', Mandatory, HelpMessage='The name of the VM scale set to create or update.')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Category('Path')]
    [System.String]
    ${VMScaleSetName},

    [Parameter(ParameterSetName='UpdateViaIdentity1', Mandatory, ValueFromPipeline, HelpMessage='Identity Parameter')]
    [Parameter(ParameterSetName='UpdateViaIdentityExpanded1', Mandatory, ValueFromPipeline, HelpMessage='Identity Parameter')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Models.IComputeIdentity]
    ${InputObject},

    [Parameter(ParameterSetName='Update1', ValueFromPipeline, HelpMessage='Describes a Virtual Machine Scale Set.')]
    [Parameter(ParameterSetName='UpdateViaIdentity1', ValueFromPipeline, HelpMessage='Describes a Virtual Machine Scale Set.')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.Compute.Models.Api20190301.IVirtualMachineScaleSet]
    ${Parameter},

```
There are a few problems:

- Both InputObject and Parameter both have 'ValueFromPipeline' set int he same parameter set, which is not possible to bind
- `Parameter` is the name of the body parameter (instead of InputObject
### I think the parameter set should be:
- Path Parameters + Flattened body parameters
- IdentityObject + Flattened body parameters

Where, in the second parameter set, if the object is a Vmss, we override its properties with the other parameters that are set.  Or, thinking about it another way, we use this object as the body parameter and substitute the provided parameters

### Update cmdlets

For Update (PATCH)

The same pattern occurs.  I think the proper pattern is:

- Path parameters + Optional flattened body parameters
- ComputeIdentityObject (from pipeline) + optional flattened body parameters

In this case, the semantics should be to always use the input object only for its identity (and potentially, ETags)

**Comment by markcowl** [comment]
This is occuriing in the latest compuet spec (examples from Set/Updat-Vmss): https://github.com/Azure/azure-powershell/blob/generation/src/Compute/readme.md

**Comment by markcowl** [comment]
@fearthecowboy I think tha, for `Update` cmdlets we have a wowrking model, and perhaps for `New` as well.

For set cmdlets, the simplest solution may be to remove `ViaIdentity` parameter sets, and ensure that the type converter allows piping to the non-expanded parameter sets.

**Comment by fearthecowboy** [comment]
Short term:
 - remove non expanded variants

Longer: 
 - have a varaiant that is like via identity but gets path from values in object

**Comment by markcowl** [comment]
For now, we will just remove the non-expanded parameter sets for Set

**Comment by fearthecowboy** [comment]
Closing; no more immediate work
