### ISSUE TITLE
Boolean Swagger Parameters -> Boolean parameters in PUT calls instead of Switch parameters

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#316]
In Az.Compute\\Set-AzVmExtension parameter `AutoUpgradeMinorVersion` is represented as a boolean instead of a switch

**Comment by fearthecowboy** [comment]
Arg. Yeah, my fault.

Which brings up the question -- If the boolean is required, does that mean the user has to say either `-SomeSwitch` or  `-SomeSwitch:$false` ?

**Comment by fearthecowboy** [comment]
I updated the generator to use switch statements for booleans. 

(2.0.469+)

**Comment by dolauli** [comment]
The issue has been fixed.
