### ISSUE TITLE
SkipSSL flag

### ISSUE THREAD

**Issue by thetonymaster** [Azure/autorest.powershell#32]
Can we get support for a SkipSSL flag? We are currently working on a version of this for Nutanix and some of the environments have self-signed, thanks!

**Comment by JonKohler** [comment]
Thanks @thetonymaster ... @fearthecowboy specifically we're talking about supporting a system whose default non-production state has self-signed certificates ... which of course means some non-security-aware customers just leave the self-signed certificates in place in production (nothing we can do about that).

That means our customers would need the ability to ignore SSL validity if they so choose

VMware does this like this. 

When you go connect to an environment, with `Connect-VIServer`, it will warn/block unless you override with `Set-PowerCLIConfiguration -InvalidCertificateAction <BadCertificateAction>`

Which they define like this (below). Not saying that VMW is the gold standard for this, just anecdotally thats how others have solved this 

> Define the action to take when an attempted connection to a server fails due to a certificate error. The following values are valid: 
> 
> Unset - this is the default value and it acts as a "Warn" value for Connect-VIServer and as "Prompt" for "-CloudServer". 
> 
> Prompt - if the server certificate is not trusted the cmdlet will prompt you for a course of action before it continues. There are several options: 
> Deny - no connection will be established. 
> Accept for once - accept the connection only for the current PowerCLI session. You will be prompted again if you attempt to connect to the same server from other processes. 
> Accept Permanently - the action will add this certificate as an exception in the "SSL Certificate Exceptions" user list. The Connect-VIServer and Connect-CIServer cmdlets will never prompt again what action to take for this particulate certificate and server. 
> Accept For All Users - same as above, however the exception will be added to all user lists, which is common for all Windows accounts on the current machine. 
> 
> Fail - the cmdlet will not establish connection if the certificate is not valid. 
> 
> Ignore - the cmdlet will establish the connection without taking into account that the certificate is invalid. 
> 
> Warn - the cmdlet will display a warning saying that the certificate is not valid, the reason why it is not considered valid and then will print additional information about the certificate. 
> 
> For more information about invalid certificates, run 'Get-Help about_invalid_certificates'.

https://code.vmware.com/doc/preview?id=6330#/doc/Connect-VIServer.html
https://code.vmware.com/doc/preview?id=6330#/doc/Set-PowerCLIConfiguration.html

**Comment by dolauli** [comment]
Considering it is quite easy to get an official CA (like Let's encrypt), we will not support it.
