### ISSUE TITLE
Multi-api script: API reduction (& Network)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#331]
So, to reduce the number of API versions we need (especially for Network), we can:
- Have a pipeline that runs de-duplication on all API versions (what happens currently)
- That pipeline outputs which API versions were used, and which were dropped entirely
- Then, we have the multi-API script update the multi-API files with only those API versions that were necessary

So far, for Network models, there are only 3 actual API versions, 2015-05-01-preview, 2017-10-01, and 2019-0201. The logic above would need to take these things into consideration:
- Do not remove API versions explicitly used in profiles
- Always include the latest API version

This logic could be used for all services (but Network would see the largest benefit).

**Comment by NelsonDaniel** [comment]
Fixed in https://github.com/Azure/autorest/pull/3266/files 
You can generate this file with --output-artifact=specs-used
