### ISSUE TITLE
Powershell generate-help: Export directories

### ISSUE THREAD

**Issue by t-miroos** [Azure/autorest.powershell#335]
The generate-help has a section to acquire the .\exports directory, or child directories if they are available. However, in the simple case when no child directories are available, the $directories object is set to the path name, and not the directory object. This results in an error when getting the script cmdlets, because $directory.FullName is null. Can be corrected by modifying the $directories logic to store the directory, not the path, in the else case.

**Comment by MiYanni** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/336
