### ISSUE TITLE
Storage: If-match (etag) not being generated

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#339]
The Cmdlets with `*ImmutabilityPolicy` that have a parameter called If-match (from swagger) is not generating these parameters.

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/blob.json

Search for `if-match`

**Comment by MiYanni** [comment]
Verified fixed by @niander. Closing
