### ISSUE TITLE
Model Proeprty 'DIsplayStatus' is shortened to 'DisplayStatu'

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#345]
From the compute generated code: https://github.com/Azure/azure-powershell/blob/generation/src/Compute/readme.md

Microsoft.Azure.PowerShell.Cmdlets.Compute.Models.Api20171201.IInstanceViewStatus

has property `DisplayStatu` instead of `DisplayStatus`

This is likely due to singularization of the parameter name

**Comment by fearthecowboy** [comment]
I changed the siguarization code yesterday to split compound words and singularize just the last word (instead of attempting a naive singularization on a word it doesn't recognizer).
