### ISSUE TITLE
Should we handle flattening property collisions differently?

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#352]
At least in some cases, when a property that is being flattened has the same name and type as an existing parameter in the `parent` class, it would be appropriate to use the same property for both purposes.

As a concrete example, `IVirtualMachineScaleSetExtension` is a body parameter in some extension cmdlets. It has a property called 'Name' which is the extension name.  When this is used in New/Set cmdlets, they also have path parameters corresponding to the extension name, which should also be called 'Name'.  This can cause clashes, or bad naming in the expanded parameter sets

In this case we could:

- Automatically merge any properties that have the same name and type (and print a warning/message)
- Allow the user to specify merging behavior for a type/cmdlet/module
- something else?

**Comment by fearthecowboy** [comment]
Parameter Collisions are handled on-the-fly when inlining. If a parameter is trying to get added that is already present it falls back to trying a logical combination of the ['container','member' and 'type'].

If the BODY has a parameter that is spiritually the same as the PATH parameter, that's a red flag; the body parameter shouldn't be there (it should be read only?)

I'd be nervous about merging two parameters, that's gonna get dicey.
