### ISSUE TITLE
Network admin module generation fails with "TenantResourceUri is not a member of interface" error

### ISSUE THREAD

**Issue by seyadava** [Azure/autorest.powershell#355]
I have created following readme files in powershell and specs repos: 

Powershell repo:
https://github.com/seyadava/azure-powershell/blob/users/seyadava/azsspecgen/src/Network/README.md
https://github.com/seyadava/azure-powershell/blob/users/seyadava/azsspecgen/src/readme.azurestack.md

Specs repo: 
https://github.com/seyadava/azure-rest-api-specs/blob/users/seyadava/networkspecgen/specification/azsadmin/resource-manager/network/readme.md
https://github.com/seyadava/azure-rest-api-specs/blob/users/seyadava/networkspecgen/specification/azsadmin/resource-manager/network/readme.azsautogen.md

Running “autorest” completes successfully and creates generated folder. But “build-modile.ps1” script fails with the following errors:

generated\api\Models\Api20150615\LoadBalancerProperty.cs(27,107): error CS0539: 'LoadBalancerProperty.TenantResourceUri' in explicit interface declaration is not a member of interface [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\LoadBalancerProperty.cs(6,49): error CS0535: 'LoadBalancerProperty' does not implement interface member 'ITenantResource.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\LoadBalancerProperty.cs(6,139): error CS0535: 'LoadBalancerProperty' does not implement interface member 'ITenantResourceInternal.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(48,107): error CS0539: 'PublicIPAddressProperties.TenantResourceUri' in explicit interface declaration is not a member of interface [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(6,54): error CS0535: 'PublicIPAddressProperties' does not implement interface member 'ITenantResource.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(6,149): error CS0535: 'PublicIPAddressProperties' does not implement interface member 'ITenantResourceInternal.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(50,107): error CS0539: 'VirtualNetworkProperties.TenantResourceUri' in explicit interface declaration is not a member of interface [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(6,53): error CS0535: 'VirtualNetworkProperties' does not implement interface member 'ITenantResource.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(6,147): error CS0535: 'VirtualNetworkProperties' does not implement interface member 'ITenantResourceInternal.Uri' [C:\Repos\azure-powershell\src\Network\Azs.NetworkAdmin.csproj]
C:\Repos\azure-powershell\src\Network\build-module.ps1 : Compilation failed.

**Comment by fearthecowboy** [comment]
Can you give me the whole command line you used?

**Comment by seyadava** [comment]
I just ran `autorest` command (with no parameters) from the main readme.md location (i.e., from the directory that contains https://github.com/seyadava/azure-powershell/blob/users/seyadava/azsspecgen/src/Network/README.md file)

**Comment by fearthecowboy** [comment]
Run `autorest --reset ` and try it again.

A lot of changes have been done since this was last run.

**Comment by viananth** [comment]
@fearthecowboy I retried it multiple times (with autorest --reset). Still getting into build issues.

PS D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin> .\build-module.ps1
Creating isolated process...
Cleaning build folders...
Compiling module...
generated\api\Models\Api20150615\LoadBalancerProperty.cs(30,107): error CS0539: 'LoadBalancerProperty.TenantResourceUri' in explicit interface declaration is not a member of interface [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\LoadBalancerProperty.cs(7,9): error CS0535: 'LoadBalancerProperty' does not implement interface member 'ITenantResource.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\LoadBalancerProperty.cs(8,9): error CS0535: 'LoadBalancerProperty' does not implement interface member 'ITenantResourceInternal.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(51,107): error CS0539: 'PublicIPAddressProperties.TenantResourceUri' in explicit interface declaration is not a member of interface [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(53,107): error CS0539: 'VirtualNetworkProperties.TenantResourceUri' in explicit interface declaration is not a member of interface [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(7,9): error CS0535: 'PublicIPAddressProperties' does not implement interface member 'ITenantResource.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\PublicIPAddressProperties.cs(8,9): error CS0535: 'PublicIPAddressProperties' does not implement interface member 'ITenantResourceInternal.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(7,9): error CS0535: 'VirtualNetworkProperties' does not implement interface member 'ITenantResource.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
generated\api\Models\Api20150615\VirtualNetworkProperties.cs(8,9): error CS0535: 'VirtualNetworkProperties' does not implement interface member 'ITenantResourceInternal.Uri' [D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\Azs.NetworkAdmin.csproj]
D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\build-module.ps1 : Compilation failed.
At D:\GitHub\azure-powershell\src\StackAdmin\Azs.Network.Admin\build-module.ps1:70 char:3
+   Write-Error 'Compilation failed.'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1

**Comment by sphibbs** [comment]
Closing
