### ISSUE TITLE
Azs Fabric admin module generation fails with reference errors

### ISSUE THREAD

**Issue by seyadava** [Azure/autorest.powershell#362]
Running `autorest` to generate AzS Fabric module. 

Readme files on Powershell repo:
https://github.com/seyadava/azure-powershell/blob/azsfabricmodule/src/readme.md
https://github.com/seyadava/azure-powershell/blob/azsfabricmodule/src/readme.azurestack.md

Readme files on Specs repo:
https://github.com/seyadava/azure-rest-api-specs/blob/azsfabricgen/specification/azsadmin/resource-manager/fabric/readme.azsautogen.md
https://github.com/seyadava/azure-rest-api-specs/blob/azsfabricgen/specification/azsadmin/resource-manager/fabric/readme.md

Ran `autorest` command with no parameters from directory that contains https://github.com/seyadava/azure-powershell/blob/azsfabricmodule/src/readme.md file. 
autorest successfully creates generated folder and PS scripts. Running build-module.ps1 fails with a bunch on "reference not found" errors:

Resources\Resources.Test\Properties\AssemblyInfo.cs(37,12): error CS0246: The type or namespace name 'CollectionBehaviorAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(37,12): error CS0246: The type or namespace name 'CollectionBehavior' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Properties\AssemblyInfo.cs(21,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Properties\AssemblyInfo.cs(22,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Properties\AssemblyInfo.cs(23,30): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(37,31): error CS0246: The type or namespace name 'DisableTestParallelization' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(21,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(22,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(23,30): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(21,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(22,28): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(23,30): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(22,12): error CS0579: Duplicate 'AssemblyTitle' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(31,12): error CS0579: Duplicate 'ComVisible' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(33,12): error CS0579: Duplicate 'Guid' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(35,12): error CS0579: Duplicate 'AssemblyVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources.Test\Properties\AssemblyInfo.cs(36,12): error CS0579: Duplicate 'AssemblyFileVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(20,12): error CS0579: Duplicate 'AssemblyTitle' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(25,12): error CS0579: Duplicate 'ComVisible' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(26,12): error CS0579: Duplicate 'CLSCompliant' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(27,12): error CS0579: Duplicate 'Guid' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(28,12): error CS0579: Duplicate 'AssemblyVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Resources\Properties\AssemblyInfo.cs(29,12): error CS0579: Duplicate 'AssemblyFileVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(20,12): error CS0579: Duplicate 'AssemblyTitle' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(25,12): error CS0579: Duplicate 'ComVisible' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(26,12): error CS0579: Duplicate 'CLSCompliant' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(27,12): error CS0579: Duplicate 'Guid' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(28,12): error CS0579: Duplicate 'AssemblyVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\Tags\Properties\AssemblyInfo.cs(29,12): error CS0579: Duplicate 'AssemblyFileVersion' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(10,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(11,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(12,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
obj\Debug\Azs.FabricAdmin.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Components\ApiVersionHelper.cs(15,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Components\ResourceManagerClientHelper.cs(15,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Components\ResourceManagerClientHelper.cs(16,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Entities\Policy\PolicySku.cs(15,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Entities\Resources\ResourceIdentity.cs(15,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Entities\Resources\ResourceSku.cs(15,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceManagerCmdletBase.cs(15,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceManagerCmdletBase.cs(16,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceWithParameterCmdletBase.cs(15,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceWithParameterCmdletBase.cs(16,32): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceWithParameterCmdletBase.cs(18,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\CmdletBase\ResourceWithParameterCmdletBase.cs(19,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\NewAzureDeploymentCmdlet.cs(17,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\NewAzureDeploymentCmdlet.cs(18,23): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\NewAzureDeploymentCmdlet.cs(19,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\TestAzureDeploymentCmdlet.cs(18,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\TestAzureDeploymentCmdlet.cs(19,23): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Deployments\TestAzureDeploymentCmdlet.cs(20,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\Policy\SetAzurePolicyAssignment.cs(15,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\GetAzureResourceGroupDeploymentCmdlet.cs(17,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\NewAzureResourceGroupDeploymentCmdlet.cs(16,23): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\NewAzureResourceGroupDeploymentCmdlet.cs(17,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\NewAzureResourceGroupDeploymentCmdlet.cs(20,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\RemoveAzureResourceGroupDeploymentCmdlet.cs(19,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\StopAzureResourceGroupDeploymentCmdlet.cs(19,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\TestAzureResourceGroupDeploymentCmdlet.cs(16,48): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Microsoft.Azure.Commands.ResourceManager' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]
Resources\ResourceManager\Implementation\ResourceGroupDeployments\TestAzureResourceGroupDeploymentCmdlet.cs(17,23): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [C:\Repos\azure-powershell\src\Azs.FabricAdmin.csproj]

**Comment by bganapa** [comment]
This is fixed
