### ISSUE TITLE
Single valued enum not being exposed as a parameter

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#383]
In storage we have the following object: (https://github.com/Azure/azure-rest-api-specs/blob/b1c3db5bb55995c33f299a79711a1b5f2d14596a/specification/storage/resource-manager/Microsoft.Storage/stable/2018-07-01/storage.json#L1204)

```
 "Identity": {
      "properties": {
        "principalId": {
          "readOnly": true,
          "type": "string",
          "description": "The principal ID of resource identity."
        },
        "tenantId": {
          "readOnly": true,
          "type": "string",
          "description": "The tenant ID of resource."
        },
        "type": {
          "type": "string",
          "description": "The identity type.",
          "enum": [
            "SystemAssigned"
          ],
          "x-ms-enum": {
            "name": "IdentityType",
            "modelAsString": false
          }
        }
      },
      "required": [
        "type"
      ],
      "description": "Identity for the resource."
    }
```

`Identity` is referenced in the body of `Update-AzStorageAccount` and `New-AzStorageAccount`. `Identity` is a non mandatory parameter while `Identity.Type` is mandatory and is an enum with just one valid value. The generated cmdlets do not have `-Identity` or `-IdentityType` as possible parameters.

That is, there is no way to not set `-IdentityType` (by not providing `Identity` since it is not mandatory) and there should be a way of doing that.

**Comment by fearthecowboy** [comment]
There isn't a way to automatically "do the right thing" here. 

The best we can do is you can create a partial class in the `custom` folder, and manually add a parameter that will force the `Identity` property in the body object to be set to a new instance of the `Identity` class.

> UpdateAzStorageAccount_Update1.cs 

``` csharp

namespace Microsoft.Azure.PowerShell.Cmdlets.Storage.Cmdlets
{
    public partial class UpdateAzStorageAccount_Update1 
    {
        // Workaround for the lack of a parameter being created for an object that has only a required constant.

        // add a parameter that creates the otherwise empty object.
        [System.Management.Automation.Parameter(Mandatory = false,HelpMessage = "Specify IdentityType as 'SystemAssigned'")]
        [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category(Microsoft.Azure.PowerShell.Cmdlets.Storage.ParameterCategory.Body)]
        public System.Management.Automation.SwitchParameter Identity { set {
           // if this switch is set, just use the internal setter for the Identity property 
           // and set a new Identity object, which has the Type as a constant.
          ((Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20190401.IStorageAccountUpdateParametersInternal)this.Parameter).Identity = new Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20171001.Identity();
        }}
    }
}
```

**Comment by fearthecowboy** [comment]
This pattern should get us thru preview -- we can look at options for automating this down the road maybe.

**Comment by niander** [comment]
@fearthecowboy It is working now. Thanks!

**Comment by MiYanni** [comment]
Verified fixed by @niander. Closing.
