### ISSUE TITLE
New-AzDnsZone, missing Mandatory for Location parameter

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#392]
So, to create a DNS zone, it needs (minimum) Name, SubscriptionId, ResourceGroupName, and Location. However, the generated cmdlets did not mark Location as mandatory.

![image](https://user-images.githubusercontent.com/17788297/60630054-41c76380-9dad-11e9-81c7-97e99c1352b8.png)

![image](https://user-images.githubusercontent.com/17788297/60630115-776c4c80-9dad-11e9-9c3a-385c211f077a.png)

If you look through the schema hierarchy, it should be Mandatory. `Parameters` of type `Zone` is required, `Zone` is allof `Resource`, and `Location` is required in `Resource`. Therefore, Location should be Mandatory.

https://github.com/Azure/azure-rest-api-specs/blob/c401716835d369a89f48d3886a0556d5dc18c098/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L790-L796

https://github.com/Azure/azure-rest-api-specs/blob/c401716835d369a89f48d3886a0556d5dc18c098/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L1530-L1548

https://github.com/Azure/azure-rest-api-specs/blob/c401716835d369a89f48d3886a0556d5dc18c098/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L1638-L1676

**Comment by fearthecowboy** [comment]
Oho. 

Looking into it.

**Comment by MiYanni** [comment]
It is now correctly marked as Mandatory.
