### ISSUE TITLE
Monitor: Swagger polymorphism didnt generate correctly

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#429]
https://github.com/Azure/azure-rest-api-specs/blob/cf33826d06605cde127d2241e54dd6df55e9145f/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json#L642

```
...
"discriminator": "odata.type"
"properties": {
        "odata.type": {
          "enum": [
            "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria",
            "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria"
          ],
          "x-ms-enum": {
            "name": "odatatype",
            "modelAsString": true
          },
          "description": "specifies the type of the alert criteria."
        }
      }
...
```

This "odata.type" can be two different types "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria" and "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria". It is not being correctly generated by autorest. The `New-AzMetricAlert` cmdlet expends just until "odata.type".

Another thing is that I cannot find the `DynamicMetricCriteria` generated model object

**Comment by markcowl** [comment]
What appears to be happening is that only the discriminator property is in the generated models, and neither of the implementing types are represented.

**Comment by fearthecowboy** [comment]
Good pickup @niander ... 

Turns out it was an over-aggressive optimization during model cleanup for profiles. (models that had an `allOf` where the parent preceded the child were getting skipped)

AutoRest core updated,
