### ISSUE TITLE
Change Runtime parameters to single parameter using ValueFromRemainingArguments

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#431]
This would simplify the custom script cmdlets surface. Basically, we make a single parameter that takes all remaining parameters provided to the cmdlet call. We implement some way to parse this information (as it is not stored as a Hashtable... because that would make too much sense). Mark said it is an array of object... So, we turn that into usable values in some way. Either we have a type that can accept an array of object and do the parsing for us, and has an interface to get the parameters in a more logical way. So...

- Create parameter for all generated cmdlets that uses `ValueFromRemainingArguments`
  - Make sure it still has `DontShow` on it and the `Runtime` category
- Create type for this parameter that allows array of object so it accepts the parameters
  - Create interface for this type that allows you to easily access the parameters and values provided
- Get the Runtime arguments from this parameter and use them if they are provided. Discard all other arguments.
- Verify the proxy generator correctly processes this new parameter

All the custom cmdlets should be updated after this to use the new parameter. This also allows us to take anything dynamically. So, we can add more Runtime-style parameters at any point.

**Comment by markcowl** [comment]
What is contained in the remaining arguments array is essentially the tokenized input string, in which parameter values are supplied as their underlying types, i.e.

```
@["-Foo", <FooValue>, "-Bar", "BarValue"]
```

etc.  Note that positional parameters would not have a token for the parameter name.
