### ISSUE TITLE
running autorest --help causes error

### ISSUE THREAD

**Issue by oising** [Azure/autorest.powershell#446]
Simple as it sounds: I installed `autorest@beta` and ran `autorest --help`

![image](https://user-images.githubusercontent.com/1844001/62153591-e8caec80-b2d2-11e9-8f16-ae309f7e9ac5.png)

**Comment by fearthecowboy** [comment]
Try installing the latest everything, I just fixed this yesterday :D 

`npm install -g autorest@beta ` and `autorest --reset`

**Comment by oising** [comment]
Sweet! Verified. Great job btw. I lurve this.
