### ISSUE TITLE
Disable auto "De-pluralization" of cmdlet nouns

### ISSUE THREAD

**Issue by joshspicer** [Azure/autorest.powershell#456]
Right now autorest is very opinionated and attempts to strip all plural words it can detect into its singular form.  

One such issue is it changing "Teams" (the product, proper noun) to "Team" in all instances.

`New-CsTeamsPolicy ---> New-CsTeamPolicy`

It would be best to provide a command line option to disable this feature entirely.  

@kenal-microsoft @amareshbAtMicrosoft

**Comment by markcowl** [comment]
Another option would be to only removal plurals from the 'Last' noun in a cmdlet name.  Ending in a plural noun is actually discouraged by PowerShell Guidelines.

**Comment by dolauli** [comment]
Through directive, you may rename the cmdlet, see https://github.com/Azure/autorest.powershell/blob/master/docs/directives.md#Cmdlet-Rename for details.
