### ISSUE TITLE
Update enum completers to use completer attributes instead

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#468]
Currently, we have custom logic to generate a `.Completer.cs` file of each enum type. After the `CompleterInfoAttribute` was added, it makes sense to no longer have custom logic specifically to generate the `.Completer.cs` file. Instead, it would decorate those enum properties with the `CompleterInfoAttribute` that contains the values of the enum as the script. Much, much easier to implement and maintain.

**Comment by fearthecowboy** [comment]
Should be able to remove the completer implementation and just write out `completerinfo` attributes instead.

**Comment by dolauli** [comment]
p3

**Comment by dolauli** [comment]
Done in autorest.powershell v4. PR is https://github.com/Azure/autorest.powershell/pull/1146
