### ISSUE TITLE
Clean up "HELP MESSAGE MISSING"

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#482]
Not sure why we write this to the parameter's HelpMessage. Would be better to not include the HelpMessage property instead if it is empty. I believe you cannot put an empty string for HelpMessage or PowerShell has a hissy fit.

This was from `NewAzOAuth2PermissionGrant_Create.cs` in the Resources module.
![image](https://user-images.githubusercontent.com/17788297/63205440-fe713d80-c058-11e9-976b-4019371fb43a.png)

**Comment by fearthecowboy** [comment]
When there is no help message, it should just eliminate the `HelpMessage` parameter entirely.

**Comment by dolauli** [comment]
p3

**Comment by dolauli** [comment]
Fixed.
