### ISSUE TITLE
Autorest Generator fails for Azs.Subscriptions.Admin module

### ISSUE THREAD

**Issue by viananth** [Azure/autorest.powershell#489]
I have created following readme files in powershell and specs repos:
Powershell repo:
https://github.com/viananth/azure-powershell/blob/azsautogen/src/StackAdmin/Azs.Subscriptions.Admin/readme.azurestack.md
https://github.com/viananth/azure-powershell/blob/azsautogen/src/StackAdmin/Azs.Subscriptions.Admin/readme.md
Specs repo:
https://github.com/viananth/azure-rest-api-specs/blob/azsadmin/specification/azsadmin/resource-manager/subscriptions/readme.azsautogen.md
https://github.com/viananth/azure-rest-api-specs/blob/azsadmin/specification/azsadmin/resource-manager/subscriptions/readme.md

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> cd D:\GitHub\azure-powershell\src\StackAdmin\Azs.Subscriptions.Admin
PS D:\GitHub\azure-powershell\src\StackAdmin\Azs.Subscriptions.Admin> autorest
AutoRest code generation utility [version: 3.0.5230; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\Administrator\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5534)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.648)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.374)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.424)
C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\dist\plugin-powershell.js - FAILURE  {} TypeError: Cannot read property 'schema' of undefined
    at CmdletClass.addClassAttributes (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:1263:95)
    at CmdletClass.init (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:158:10)
    at CmdletNamespace.init (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110)
PLUGIN FAILURE: Cannot read property 'schema' of undefined, TypeError: Cannot read property 'schema' of undefined
    at CmdletClass.addClassAttributes (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:1263:95)
    at CmdletClass.init (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:158:10)
    at CmdletNamespace.init (C:\Users\Administrator\.autorest\@microsoft.azure_autorest.powershell@2.0.648\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110), {}
FATAL: TypeError: Cannot read property 'schema' of undefined
C:\Users\Administrator\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin powershell reported failure. / Error: Plugin powershell reported failure.
    at C:\Users\Administrator\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin powershell reported failure.
PS D:\GitHub\azure-powershell\src\StackAdmin\Azs.Subscriptions.Admin>

**Comment by fearthecowboy** [comment]
In `"/subscriptions/{subscriptionId}/providers/Microsoft.Subscriptions.Admin/checkNameAvailability":`

You have marked the method with `x-ms-pageable` and the response is not a collection.

remove 

```
   "x-ms-pageable": {
          "nextLinkName": null
        }
```

I've added in an error when that happens.

FYI: if you haven't seen it yet, you need to change how you install autorest beta

```  powershell
# remove  old autorest-beta
npm uninstall -g autorest

#install new autorest beta packge:
npm install -g @autorest/autorest

# reset plugins
autorest-beta --reset

# now use 'autorest-beta' instead of 'autorest'
autorest-beta <...>

```

After that I ran into a problem with `New-AzsSubscription ` where it ends up having a parameter `$Id` with an alias to `$subscriptionId` and a parameter for `$subscriptionId` -- you will need to remove the alias on `$id` with

```
directive:
  - where:
      subject: Subscription
      parameter-name: id
    clear-alias: true
     
```

**Comment by viananth** [comment]
Thank you Garret, for the detailed instructions. Its fixed.
