### ISSUE TITLE
Documents and samples needed to be updated for the transition

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest.powershell#490]
Some documents and samples in the the repository Azure/autorest and Azure/autorest.powershell are probably out-of-dated or not be completed yet. And they should be updated as part of the transition. And below are some of the folders probably need to be updated (Not limited to).

- https://github.com/Azure/autorest/tree/master/docs/powershell

- https://github.com/Azure/autorest.powershell/tree/master/docs

**Comment by dolauli** [comment]
@markcowl 
This issue is created per our discussion today. Since I do not have the permission to add this issue to the release project, please help do that.

**Comment by fearthecowboy** [comment]
#546  -- adds the documentation for writing/running tests

**Comment by fearthecowboy** [comment]
#547 - add user docs to autorest-powershell
