### ISSUE TITLE
Use example information in exports

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#492]
Now that comment-based help is read as part of the build process (https://github.com/Azure/autorest.powershell/pull/491), we also read the example information since it is running the same process that is used for markdown generation. However, as part of that change, I did not update the exports to have the examples information. It shouldn't be too difficult to add, but would just need to be formatted properly into the [dot comments](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-6#example) format for examples.

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/583.
