### ISSUE TITLE
Piping select-object error

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#494]
`Get-AzMetricAlerts` returns 3 objects

`Get-AzMetricAlerts | Select -First 1` return nothing

`Get-AzMetricAlerts | Select -First 3` return nothing

`Get-AzMetricAlerts | Select -First 4` return all 3 objects

`Get-AzMetricAlerts | Select -Last 1` return the last object

`(Get-AzMetricAlerts)[0]` return the last object

@markcowl seems to have already found where in the code the bug should be

**Comment by markcowl** [comment]
This was fixed, but has regressed - we have gone back to the original exception handling pattern above.  Verified in generated code, and reported by customer here: https://github.com/Azure/azure-powershell/issues/10226

**Comment by markcowl** [comment]
P2

**Comment by dolauli** [comment]
This is not a regression issue of autorest.powershell, but need an upgrade of autorest core used in the ADO job to generate Az 4.
