### ISSUE TITLE
Configuration: Allow marking parameters as mandatory

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#498]
In certain cases, the swagger defines a schema property as non-required. However, when you actually go to run the rest call, it says something like: 
```json
Body:
{
  "error": {
    "code": "LocationRequired",
    "message": "The location property is required for this definition."
  }
}
```

So, obviously, `Location` is required here, but it was marked as optional in the swagger.

**Comment by fearthecowboy** [comment]
Should be able to add configuration on parameters to set the required flag to true.

**Comment by dolauli** [comment]
p4

**Comment by dolauli** [comment]
We may change the swagger with directive on the fly.
