### ISSUE TITLE
Need a cmdlet to Interogate an extension for valid properties to pass.

### ISSUE THREAD

**Issue by jlongo62** [Azure/autorest.powershell#513]
Related to this thread:
https://github.com/MicrosoftDocs/azure-docs/issues/39274#issuecomment-533590718

Documentation is always out of date, but if you can  ask an Extension to reflect it's properties. you mitigate most of the issue. This information can also be used to create a template for a documentation page so properties are not missed. See the thread. Perhaps properties could be returned as part of: Get-AzureVMAvailableExtension

**Comment by dolauli** [comment]
Not valid any more.
