### ISSUE TITLE
Need to handle 'preview' module versions in psd1 and nupkg generation

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#514]
The generator should automatically handle preview syntax for mosule versions.  In this case, the convention for preview syntax is any text after a `-` in the version name.

Since the PowerShell engine can only handle numeric versions in the module manifest, this is represented differently in the generated nuspec file and the generated psd1 file.

- In the psd1 file, for any version that contains a dash `-` character
  - The version should be split into the parts before and after the first dash `<first-part>-<second-part>`
  - If the *first-part* cannot be parsed into a windows version (i.e. `x.y.z` or `x.y.z.w`) then throw an error that the version is illegal
  - if the *second-part* is null or whitespace, throw an error that the version is illegal
  - Place the *first-part* in the Moduleversion field in the psd1 file
  - Add a key/value pair to the `PrivateData\PSData` section of the PSD1 file , with the *second-part* as the value, i.e.
    ```
    Prerelease = "<second-part>"
    ```
- In the NuSpec file, simply transmit the version as is to the file.

This will be necessary for future versions of the modules - right now, this is being done through code changes in the config files for affected modules.

**Comment by dolauli** [comment]
Already resolved
