### ISSUE TITLE
Export-ProxyCmdlet error

### ISSUE THREAD

**Issue by stefanstranger** [Azure/autorest.powershell#518]
When trying to build the PowerShell module with the command .\build-module.ps1 I get the following error:

Export-ProxyCmdlet : The parameter 'Password' has multiple parameter types [IBodyParameterLoginRequestBody, String] defined, which is not supported.

[Link to swagger document](https://gist.github.com/stefanstranger/66a2c5c29cf8f96aab500ba0de525a63).

Autorest version:
AutoRest code generation utility [version: 3.0.5231; node: v10.15.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions
 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4399     C:\Users\stefstr\.autorest\@microsoft.azure_autorest-core@2.0.4399
 core       @microsoft.azure/autorest-core           3.0.5537     C:\Users\stefstr\.autorest\@microsoft.azure_autorest-core@3.0.5537
 extension  @microsoft.azure/autorest.csharp-v2      2.0.433      C:\Users\stefstr\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.433
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\stefstr\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\stefstr\.autorest\@microsoft.azure_autorest.modeler@2.3.55
 extension  @microsoft.azure/autorest.powershell     2.0.678      C:\Users\stefstr\.autorest\@microsoft.azure_autorest.powershell@2.0.678
 extension  @microsoft.azure/autorest.remodeler      2.0.382      C:\Users\stefstr\.autorest\@microsoft.azure_autorest.remodeler@2.0.382

**Comment by dolauli** [comment]
Generator will generate two versions for API with request body -- expanded and unexpanded versions.
And you may only keep one version. For Azure PowerShell, our practice is to keep the expanded version. So you will need add following code in under directive in readme.md.
```
 - where:
      variant: ^Create$|^CreateViaIdentity$|^Update$|^UpdateViaIdentity$
    remove: true
```

**Comment by joeskeen** [comment]
@dolauli I had a very similar error and tried to use the solution you provided, but it didn't make a difference to the error.  How do you derive that solution?  Is the variant dependent on information from the swagger (the OP's swagger is no longer available).
Also, as a user, I expected that I could just generate the client and build it without modifications.  Is there any way we could pass a parameter into the generation that will only generate the expanded or unexpanded versions?  I really try to avoid modifying generated code as modifications are gone when you re-generate...

**Comment by asumner** [comment]
> 

This is mad, where can we turn off these duplicate api 'expanded' versions?
In what 'readme.md' file, crazy. I don't mind reading the docs but where to start!
