### ISSUE TITLE
Generated Powershell client case sensitivity

### ISSUE THREAD

**Issue by jeremy-collette** [Azure/autorest.powershell#521]
The current behaviour for the generated Powershell client is to have case sensitive object property names.

For example, if the swagger spec defines a title cased property in an object, the property will be ignored if the returned object has property names in camel case (or any other unexpected case).

Is this expected behaviour?

**Comment by dolauli** [comment]
@jeremy-collette Would you please provide a sample swagger file?

**Comment by imjuststeve** [comment]
@jeremy-collette - did you get a solution for this? I'm hitting the same issue.

**Comment by jeremy-collette** [comment]
> @jeremy-collette - did you get a solution for this? I'm hitting the same issue.

@imjuststeve From memory I changed the casing of the swagger spec as a workaround

**Comment by dolauli** [comment]
It looks like an issue of swagger.
