### ISSUE TITLE
Individual PS1 files cause module bloat when signed

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#524]
In the current design, there is a PS1 file for every cmdlet in each profile, represented as a `.ps`` file.  In modules with many cmdlets (for example, AppService), this causes the module size to explode when these files are authenticode signed.

Consider alternatives for individual ps1 files - for example, since each cmdlet is a function, many cmdlets can be written to the same file in exports.

**Comment by dolauli** [comment]
p2 not urgent

**Comment by dolauli** [comment]
Resolved
