### ISSUE TITLE
name conflict when two parent interfaces contain same property

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.powershell#531]
The error happens when generating Cmdlets for Aks.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-06-01/managedClusters.json#L1474

**Comment by dolauli** [comment]
@erich-wang Would you give more explanation on this issue?

**Comment by dolauli** [comment]
Verified the issue has been fixed in 3.0.403
