### ISSUE TITLE
Generated commands of type function are exported as cmdlets in module manifest

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#556]
Generated commands of type function are being exported under `CmdletsToExport` in the module manifest. Ideally, they should be exported as functions under `FunctionsToExport` in a `.psd1`.

**Repro:**
1. Install `Az.Compute` module.
2. Run Get-Command -Module Az.Compute. You will notice that the commandType of generated commands are functions, yet [Az.Compute module manifest](https://www.powershellgallery.com/packages/Az.Compute/4.0.2-preview/Content/Az.Compute.psd1) exports them as cmdlets.
![image](https://user-images.githubusercontent.com/7061532/72575342-ec523000-3880-11ea-9448-8ed84b70ee1e.png)

![image](https://user-images.githubusercontent.com/7061532/72575380-0c81ef00-3881-11ea-9c4f-938306609fcb.png)

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/76

**Comment by KirkMunro** [comment]
Just to expand on this, not only should the command types be properly identified (i.e. the command names must be assigned to the appropriate `*ToExport` value in the manifest), any of the `*ToExport` values in the manifest that do not have any commands must be assigned to an empty array.

For example, if a module generated using AutoRest does not publish any cmdlets, then the manifest must contain `CmdletsToExport = @()`.

Explicit assignment (to an empty array in this case) is necessary for performance when PowerShell attempts to discover the commands contained within a module. If PowerShell cannot tell what commands are exported from a module via inspection of the manifest, it looks deeper into the module itself, and that additional work is expensive, so explicit assignment is the way to go here.

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/583.
