### ISSUE TITLE
[AzureStack] DateTime query paramater missing in the URL

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#559]
This is the swagger document 
https://github.com/Azure/azure-rest-api-specs/blob/e61f973eef60cedcdaf571fe504ad8f2297f141a/specification/azsadmin/resource-manager/commerce/Microsoft.Commerce.Admin/preview/2015-06-01-preview/Commerce.json#L292

In the generated code i see that the ReportedStartTime and ReportedEndTIme string are not appended while constructing the URL.

Could you please help how we can fix this issue?

## Generated code 
// construct URL
                var _url = new global::System.Uri(global::System.Text.RegularExpressions.Regex.Replace(
                        "https://management.azure.com/subscriptions/"
                        + global::System.Uri.EscapeDataString(subscriptionId)
                        + "/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates"
                        + "?"
                        + "api-version=" + global::System.Uri.EscapeDataString(apiVersion)
                        + "&"
                        + reportedStartTime.ToString(@"yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK",global::System.Globalization.CultureInfo.InvariantCulture)
                        + "&"
                        + reportedEndTime.ToString(@"yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK",global::System.Globalization.CultureInfo.InvariantCulture)
                        + "&"
                        + (string.IsNullOrEmpty(aggregationGranularity) ? global::System.String.Empty : "aggregationGranularity=" + global::System.Uri.EscapeDataString(aggregationGranularity))
                        + "&"
                        + (string.IsNullOrEmpty(subscriberId) ? global::System.String.Empty : "subscriberId=" + global::System.Uri.EscapeDataString(subscriberId))
                        + "&"
                        + (string.IsNullOrEmpty(continuationToken) ? global::System.String.Empty : "continuationToken=" + global::System.Uri.EscapeDataString(continuationToken))
                        ,"\\?&*$|&*$|(\\?)&+|(&)&+","$1$2"));

## Debug Logs

PS C:\> Get-AzsSubscriberUsageAggregate -ReportedStartTime $start -ReportedEndTime $end 
DEBUG: 2:15:55 PM - GetAzureRMContextCommand end processing.
DEBUG: 2:15:55 PM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzsSubscriberUsageAggregate_List': AzureQoSEvent: CommandName - Get-AzsSubscriberUsageAggregate_List; IsSuccess - False; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://management.azure.com/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-version=2015-06-01-preview&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00
DEBUG: RequestCreated: https://management.azure.com/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-version=2015-06-01-preview&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-version=2015-06-01-preview&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-version=2015-06-01-preview&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00

Headers:

Body:

DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 14577
x-ms-request-id               : 2013af7c-86f4-4ec0-b5d8-b6f7321d1019
x-ms-correlation-request-id   : 2013af7c-86f4-4ec0-b5d8-b6f7321d1019
x-ms-routing-request-id       : NORTHWEST:20200121T221555Z:2013af7c-86f4-4ec0-b5d8-b6f7321d1019
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 21 Jan 2020 22:15:55 GMT
X-Powered-By                  : ASP.NET

Body:
{
  "message": "No HTTP resource was found that matches the request URI 'https://adminproviders.azs-long02-int.selfhost.corp.microsoft.com:30022/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-version=2015-06-01-previ
ew&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00'."
}

DEBUG: ResponseCreated: 
DEBUG: Finally: 
Get-AzsSubscriberUsageAggregate : No HTTP resource was found that matches the request URI 'https://adminproviders.azs-long02-int.selfhost.corp.microsoft.com:30022/subscriptions/74c72bdc-d917-431c-a377-8ca80f4238a0/providers/Microsoft.Commerce.Admin/subscriberUsageAggregates?api-ver
sion=2015-06-01-preview&2020-01-16T14:15:40.9858632-08:00&2020-01-21T14:15:40.9858632-08:00'.
At line:1 char:1
+ Get-AzsSubscriberUsageAggregate -ReportedStartTime $start -ReportedEn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionI...ationToken =  }:<>f__AnonymousType0`6) [Get-AzsSubscriberUsageAggregate_List], UndeclaredResponseException
    + FullyQualifiedErrorId : NotFound,Microsoft.Azure.PowerShell.Cmdlets.CommerceAdmin.Cmdlets.GetAzsSubscriberUsageAggregate_List
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Get-AzsSubscriberUsageAggregate_List': AzureQoSEvent: CommandName - Get-AzsSubscriberUsageAggregate_List; IsSuccess - True; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing:

**Comment by markcowl** [comment]
Can you also provide the configuration file you are using ( a link is fine)

**Comment by markcowl** [comment]
This appears to be a bhard bug that we should fix, in which query parameters using format 'datetime' are not serialized correctly into the uri string (query value is provided, but no query key).

It is possible to fix this with a customization, but we should fix in Autorest, if possible

**Comment by dingmeng-xue** [comment]
@bganapa has verified that and issue is resolved.
