### ISSUE TITLE
[AzureStack] Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#560]
Build-module.ps1 is failing with the following . It looks like an issue with the nuget settings. Why would it look for PowershellStandard.Library. Any tips for troubleshooting?
 
PS C:\Repos\AzureStack-AzsAdmin\azure-powershell\src\StackAdmin\Azs.InfrastructureInsights.Admin> .\build-module.ps1
Creating isolated process...
Cleaning build folders...
Compiling module...
C:\Program Files\dotnet\sdk\2.2.401\NuGet.targets(123,5): error : Failed to retrieve information about 'PowerShellStandard.Library' from remote source 'https://msazure.pkgs.visualstudio.com/_packaging/Official/nuget/v2/FindPackagesById()?id='PowerShellStandard.Library'&semVerLevel=2.0.0'. [C:\Repos\AzureStack-AzsAdmin\azure-powershell\src\StackAdmin\Azs.InfrastructureInsights.Admin\Azs.InfrastructureInsights.Admin.csproj]
C:\Program Files\dotnet\sdk\2.2.401\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Repos\AzureStack-AzsAdmin\azure-powershell\src\StackAdmin\Azs.InfrastructureInsights.Admin\Azs.InfrastructureInsights.Admin.csproj]
C:\Repos\AzureStack-AzsAdmin\azure-powershell\src\StackAdmin\Azs.InfrastructureInsights.Admin\build-module.ps1 : Compilation failed.
At C:\Repos\AzureStack-AzsAdmin\azure-powershell\src\StackAdmin\Azs.InfrastructureInsights.Admin\build-module.ps1:85 char:5
 Write-Error 'Compilation failed.'
 CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
 FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1

**Comment by dolauli** [comment]
This should be an environment related issue, which has nothting to do with the PowerShell generator.
