### ISSUE TITLE
[Stack] [GalleryAdmin] Piping is broken for Get-AzsGalleryItem to Remove-AzsGalleryItem

### ISSUE THREAD

**Issue by viananth** [Azure/autorest.powershell#561]
Get-AzsGalleryItem -Name <blah> | Remove-AzsGalleryItem results in invalid identity URI

		Remove-AzsGalleryItem : Invalid identity for URI
		'/subscriptions/{subscriptionId}/providers/microsoft.gallery.admin/galleryItems/{galleryItemName}'
		At line:1 char:1
		+ Get-AzsGalleryItem -Name TestUbuntu.Test.1.0.0 | Remove-AzsGalleryIte ...
		+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		    + CategoryInfo          : NotSpecified: (:) [Remove-AzsGalleryItem_DeleteViaIdentity], Exception
		    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.Gallery.Cmdlets.RemoveAzsGalleryItem_DeleteViaIdentit
		   y
		
		Debug log:
		DEBUG: CmdletProcessRecordStart:
		DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Remove-AzsGalleryItem_DeleteViaIdentity':
		AzureQoSEvent: CommandName - Remove-AzsGalleryItem_DeleteViaIdentity; IsSuccess - False; Duration - 00:00:00; Exception
		 - ;
		DEBUG: CmdletProcessRecordAsyncStart:
		DEBUG: CmdletGetPipeline:
		DEBUG: CmdletBeforeAPICall:
		DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Remove-AzsGalleryItem_DeleteViaIdentity':
		AzureQoSEvent: CommandName - Remove-AzsGalleryItem_DeleteViaIdentity; IsSuccess - True; Duration - 00:00:00; Exception
		- ;
		DEBUG: CmdletProcessRecordAsyncEnd:
		DEBUG: [CmdletException]: Received Exception with message 'Exception - Invalid identity for URI
		'/subscriptions/{subscriptionId}/providers/microsoft.gallery.admin/galleryItems/{galleryItemName}' :    at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.GalleryManagementClient.<GalleryItemsDeleteViaIdentity>d__5.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		   at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.Cmdlets.RemoveAzsGalleryItem_DeleteViaIdentity.<ProcessRecordAsync>d__59.Mov
		eNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.Cmdlets.RemoveAzsGalleryItem_DeleteViaIdentity.<ProcessRecordAsync>d__59.Mov
		eNext()'
		DEBUG: CmdletException: Exception - Invalid identity for URI
		'/subscriptions/{subscriptionId}/providers/microsoft.gallery.admin/galleryItems/{galleryItemName}' :    at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.GalleryManagementClient.<GalleryItemsDeleteViaIdentity>d__5.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		   at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.Cmdlets.RemoveAzsGalleryItem_DeleteViaIdentity.<ProcessRecordAsync>d__59.Mov
		eNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at
		Microsoft.Azure.PowerShell.Cmdlets.Gallery.Cmdlets.RemoveAzsGalleryItem_DeleteViaIdentity.<ProcessRecordAsync>d__59.Mov
		eNext()

**Comment by viananth** [comment]
The issue is, during validation of the resource URI, the regex used doesn't use "ignore case" and the URI validation fails because of the case sensitivity:

`
                var _match = new global::System.Text.RegularExpressions.Regex("^/subscriptions/(?<subscriptionId>[^/]+)/providers/microsoft.gallery.admin/galleryItems/(?<galleryItemName>[^/]+)$").Match(viaIdentity);
`

The actual resource ID was: 
`
/subscriptions/xxxxxxxxxxxxxxxxxx/providers/Microsoft.Gallery.Admin/galleryItems/xxxxxxxxxxxxxx
`

The fix would be to update the generator to check URI with "ignore case".

**Comment by markcowl** [comment]
Discussed offline. This is another issue where a body property and a uri parameter have the same value.  We maight address this if we implement a general parameter mapping mechanism, but otherwise, this pattern requires a customization (they must create a custom cmdlet without the additional parameter, and populate it in code based on the input object)..

**Comment by viananth** [comment]
Thank you Mark. We fixed it in the spec and works fine now.
