### ISSUE TITLE
[AzureStack: Subscription Admin] Get parameter value from the Pipeline object

### ISSUE THREAD

**Issue by rakku-ms** [Azure/autorest.powershell#562]
Set-AzsOffer require Name parameter even when Name parameter is available as part of the pipeline object $offer

$allOffers = Get-AzsAdminManagedOffer
$offer = $allOffers[0]
$offer | Set-AzsOffer

e.g.
```
ConvertTo-Json $offer -Depth 5
{
    "AddonPlans":  [

                   ],
    "BasePlanIds":  [
                        "/subscriptions/63d29070-44b8-4cbb-953f-4a50dc1b4ad7/resourceGroups/DRPTestResourceGroup4693/providers/Microsoft.Subscriptions.Admin/plans/DRPTestPlan4693"
                    ],
    "Description":  "",
    "DisplayName":  "DRPTestOffer4693-test",
    "ExternalReferenceId":  "",
    "Id":  "/subscriptions/63d29070-44b8-4cbb-953f-4a50dc1b4ad7/resourceGroups/DRPTestResourceGroup4693/providers/Microsoft.Subscriptions.Admin/offers/DRPTestOffer4693",
    "Location":  "redmond",
    "MaxSubscriptionsPerAccount":  0,
    "Name":  "DRPTestOffer4693",
    "PropertiesName":  "DRPTestOffer4693",
    "State":  {

              },
    "SubscriptionCount":  1,
    "Tags":  {

             },
    "Type":  "Microsoft.Subscriptions.Admin/offers"
}
```

**Comment by markcowl** [comment]
Need additional information, particularly a uri to the spec and config you are using

**Comment by markcowl** [comment]
Discussed offline, this will be fixed with a customization.  The underlying issue is that the swagger spec has two required properties (one in the path, one in the body) that are actually the same value.  If we ever add additional configuration to allow remapping parameter values, then we might fix this.

**Comment by rakku-ms** [comment]
Fixed with customization
