### ISSUE TITLE
[AzureStack: Subscription Admin] Rest call successful but cmdlet failing with ' Cannot access a disposed object' error

### ISSUE THREAD

**Issue by rakku-ms** [Azure/autorest.powershell#563]
Fiddler showing successful 200 code for New-AzsAcquiredPlan but the cmdlet is failing

$plans = Get-AzsPlan
$plan = $plans[0]
$acquisitionId = ([Guid]::NewGuid()).Guid
$targetSubscriptionId = "89d3387e-d050-4769-a15f-2d9f0dd85015"

New-AzsAcquiredPlan -PlanAcquisitionId $acquisitionId -PlanId $plan.Id -TargetSubscriptionId $targetSubscriptionId -AcquisitionId $acquisitionId

```
New-AzsAcquiredPlan : Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
At line:1 char:1
+ New-AzsAcquiredPlan -PlanAcquisitionId $global:acquisitionId -PlanId  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzsAcquiredPlan_CreateExpanded], ObjectDisposedException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.NewAzsAcquiredPlan_CreateExpanded
```

**Comment by markcowl** [comment]
Need additional info to diagnose, particuarly:

(1) Run the command with $DebugPreference="Continue"
(2) Get the full exception details using Resolve-AzError

**Comment by markcowl** [comment]
This is currently no repro, Stack team will update when they have a repro themselves
