### ISSUE TITLE
Generations should default to Format-List instead of Format-Table

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#564]
By default , autorest generator is doing format-table and generating a *format.ps1xml. 

In most of the cases , for azure stack we are in need of doing suppress-format for various models as there are too many equally important fields that we want to show up.
i believe this would be the case for many other components.

Can you please consider doing format-list as the default instead of forcing every cmdlet to do output formatting?

**Comment by dolauli** [comment]
By default, powershell uses format-table. And if you need the list format, please pipe your result to | fl
