### ISSUE TITLE
New-* cmdlets are idempotent, not throwing  error when resource already exists

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#565]
By default, we see that New-* cmdlet overwrites the existing resource instead of complaining that the resource already exists. 

Our existing modules shows error like below. 

New-AzsNetworkQuota : A network quota with the name ExampleQuota at location northwest already exists

As per the discussion with Mark, Resource already error could be thrown easily if the API supports if-none-match:* header indicating the PUT operation to fail if the resource already exists

**Comment by dolauli** [comment]
It is duplicated with https://github.com/Azure/autorest.powershell/issues/569.
