### ISSUE TITLE
latest autorest/powershell extension failing for .\build-module.ps1

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#567]
After installing latest autorest with autorest-beta –reset, the build is failing while doing  .\build-module.ps1 . Could you please look in to this? I am not sure whether this is an issue with autorest-beta or the powershell extension

Previously we were using the following versions and I tried using the specific version with the following. I am doing something wrong here as it still pulled the 2.1.355 version of autorest . Could you please let me know how I could install the older version to unblock us while you are looking in to the issue?
Autorest-beta –version:3.0.6148
npm install @autorest/powershell@2.1.329

To repro, from azure-powershell repo, please do the following

git fetch upstream
git checkout -b stackadmin upstream/stackadmin
autorest-beta –reset
cd src\stackadmin\azs.network.admin
autorest-beta
pwsh
.\build-module.ps1

![image](https://user-images.githubusercontent.com/12038849/73705131-e7c3af00-46a9-11ea-9a51-59452d5d4f34.png)

**Comment by dolauli** [comment]
There are regression issues in the autorest/autorest.core, and it should have been fixed now. If you still find the issue, please file an issue in the autorest repo.
