### ISSUE TITLE
[Stack][Azs.InfrastructureInsights.Admin] Close alert fails

### ISSUE THREAD

**Issue by BenDavMS** [Azure/autorest.powershell#568]
Close-AzsAlert isnt passing through a properties object in the body which is failing in HRP as the resourceProperties object (required) is null

$aa[0] | Close-AzsAlert -Location redmond -User "foobar@msazurestack.onmicrosoft.com"
Close-AzsAlert : The server responded with a Server Error, Status: BadGateway
At line:1 char:1
+ $aa[0] | Close-AzsAlert -Location redmond -User "foobar@msazu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ User = ciserv...0160501.Alert }:<>f__AnonymousType1`2) [Close-AzsAl
   ert_CloseViaIdentityExpanded], UndeclaredResponseException
    + FullyQualifiedErrorId : BadGateway,Microsoft.Azure.PowerShell.Cmdlets.InfrastructureInsightsAdmin.Cmdlets.CloseA
   zsAlert_CloseViaIdentityExpanded

**Comment by dolauli** [comment]
Looks there is a service side error. Please add the switch "-debug" for detailed logs. @BenDavMS

**Comment by BenDavMS** [comment]
[debugoutput.txt](https://github.com/Azure/autorest.powershell/files/4169356/debugoutput.txt)

**Comment by dingmeng-xue** [comment]
@BenDavMS , could you try again? The log shows it is service side problem.

**Comment by dolauli** [comment]
Close it since no further response from the reporter.
