### ISSUE TITLE
Update the Az.Accounts version emitted by the powershell generator

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#573]
Updating to the MSAL az.accounts version would help us run the Pester test without any changes

**Comment by bganapa** [comment]
@dolauli @markcowl Issue is filed as we discussed in the meeting

**Comment by bganapa** [comment]
@dolauli @markcowl , I added the ModuleVersion dependency on Az.Accounts module 2.0.1-preview in the admin modules and  the build started to fail in the pipeline

Can you please look in to this issue?

can be reproed by doing .\build-module -Docs -Release

--------------------------------------------------------------------------------------
Creating exports and docs...
Creating format.ps1xml...
Creating psd1...
Creating test stubs...
Creating example stubs...
-------------Done-------------
Creating isolated process...
Import-Module : The required module 'Az.Accounts' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'D:\a\1\s\src\Azs.Commerce.Admin\Azs.Commerce.Admin.psd1'.
At D:\a\1\s\src\Azs.Commerce.Admin\generate-help.ps1:48 char:1
+ Import-Module -Name $modulePath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (D:\a\1\s\src\Azs.Co\u2026Commerce.Admin.psd1:String) [Import-Module], MissingMemberException
+ FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by dolauli** [comment]
@bganapa You need to install and load Az.Accounts module 2.0.1-preview as suggested by the error in the build machine.

**Comment by bganapa** [comment]
2.0.1-preview is not yet released, can you pls package that version part of autorest powershell generator?

**Comment by dolauli** [comment]
@bganapa I can not do that, since there are other teams are using the generator. And I have updated it to the latest GA version 1.7.2. Following is a workaround for you to run the pester test with 2.0.1-preview in ADO.

1. Add a task to install the 2.0.1-preview
2. In readme.azurestack.md, add following code.
  `- from: test-module.ps1`
    `where: $`
    `transform: return $.replace("$ProgressPreference = 'SilentlyContinue'", "$ProgressPreference = 'SilentlyContinue'\nImport-Module -Name Az.Accounts")`

**Comment by bganapa** [comment]
@dolauli We will do that . Thanks!

**Comment by dolauli** [comment]
Already update the dependency to Az.Accounts 1.7.4
