### ISSUE TITLE
Get-* commands should return nothing for non existing resources

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#578]
Currently it throws 404 Not found . The generator should emit code to catch this exception and return nothing

**Comment by dolauli** [comment]
The generator will not suppress any error from the service side. But you may customize the function overrideOnNotFound to do that. And the generator will generate the prototype of the partial method overrideOnNotFound, if 404 is defined as a potential error response in the swagger.

**Comment by bganapa** [comment]
@markcowl  We prefer to have this capability by default in auotrest generator insted of customization
@dolauli
