### ISSUE TITLE
autorest generated does not throw the exception for a failed azure async operation

### ISSUE THREAD

**Issue by daozha** [Azure/autorest.powershell#580]
We have a PUT call that will be tracked by Azure async operation and the final response would be 200 with the following body:
 ![image](https://user-images.githubusercontent.com/38281880/75774851-cbd82980-5d8b-11ea-9105-c8370c15a7c6.png)

We expect the client report the error, but seems client called another GET to the original uri. We looked into the log and code and found that client did notice the provisioning state to be Failed:
 ![image](https://user-images.githubusercontent.com/38281880/75774869-d8f51880-5d8b-11ea-940f-2ede107ecc1a.png)

While seems the final GET call happens in onOk:
 ![image](https://user-images.githubusercontent.com/38281880/75774912-edd1ac00-5d8b-11ea-9aab-df454423a90b.png)

**Comment by isra-fel** [comment]
Root cause:
In the logic of polling inside generated code, we are handling the "failed" and "cancelled" provisioning states the same way as "succeeded". They should throw error.

```csharp
                                    switch( state?.ToString()?.ToLower() )
                                    {
                                      case "succeeded":
                                      case "failed":
                                      case "canceled":
                                        // we're done polling.
                                        break;

                                      default:
                                        // need to keep polling!
                                        _response.StatusCode = global::System.Net.HttpStatusCode.Created;
                                        continue;
                                    }
```
