### ISSUE TITLE
How to properly enable multi-profile support

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#587]
I've been investigating profile support in our PowerShell SDK, and so far, I've encountered the following issue that is blocking us.

AutoREST seems to be generating profiles based on the last input file when multiple input files are specified. This can be reproed by cloning https://github.com/peombwa/Multi-Profile.git and running `autorest --verbose` then `.\build-module.ps1` while in `.\src\Users.Mail\` directory.

From the logs, it's clear that AutoREST reads the two input files, but only generates one profile for the last input file - `/beta/users.mail.yml`.
![image](https://user-images.githubusercontent.com/7061532/78810755-a091bd00-797d-11ea-9a12-5bd4018d2b75.png)

Switching the order of the input-files will generate the last profile - `/v1.0/users.mail.yml`..
![image](https://user-images.githubusercontent.com/7061532/78810956-f5cdce80-797d-11ea-8695-93506ad89c93.png)

**Comment by peombwa** [comment]
cc @dolauli

**Comment by dolauli** [comment]
The latest autorest.core seems to fix the issue.
Run "autorest-beta --reset" to clear the old core extension in order to apply the new.
