### ISSUE TITLE
autorest --azure flag isn't simplifying the name parameter for listkeys/regeneratekeys cmdlets

### ISSUE THREAD

**Issue by jlautman** [Azure/autorest.powershell#588]
The --azure flag typically simplifies parameters such as `-<Resource>Name` to -Name, with an alias to `-<Resource>Name`. This works for most generated cmdlets. However, listkeys and regeneratekeys cmdlets (`Get-Az<resource>Key` and `New-Az<resource>Key`) are not honoring this simplification. This introduces an inconsistency with parameter naming.

**Comment by dolauli** [comment]
The design is not as you describe.
If the cmdlet is xxx-az<Resource> and 'Name' is resource name, we will simplify it to '-Name' from '-<Resource>Name'. But if the cmdlet is xxx-az<Resource>xxx, we will use '-<Resource>Name'.
BTW, Get-AzKey and New-AzKey are not good names, you should name them to Get-AzSpoolKey and New-AzSpoolKey. And the change will make it easy for the users to find the cmdlets.

**Comment by jlautman** [comment]
Sorry. There was `<resource`> in those names but it was hidden by markdown. In our case we're naming them Get-AzSpoolKey and New-AzSpoolKey. When I generate the SDK the parameter-name SpoolName is not being changed to Name like it is for the rest of our cmdlets.

**Comment by dolauli** [comment]
Yes, for these two cmdlets, we will not change SpoolName to Name, it is by design. 
If the cmdlet is 'Get-AzSpoolKey -Name', "Name" here normally means SpoolKeyName instead of SpoolName.

**Comment by jlautman** [comment]
Right now it's generating -SpoolName, not -SpoolKeyName.

This Cmdlet allows for calling the listkeys and regeneratekey POST actions on a Spool resource, not for accessing a sub-resource under Spool. Name here should mean the name of the spool resource on which the operation is performed.

**Comment by jlautman** [comment]
This is a direct result of the design decision to represent the POST action operations `<resource>_RegenerateKey` and `<resource>_ListKeys` as `New-Az<resource>Key` and `Get-Az<resource>Key` respectively. However, despite the powershell name mapping, regeneratekey is not creating a nested resource and listkeys is not a list operation. They are both POST actions on a resource and should behave as such.

Since they're both POST actions, the parameter naming should match the resource they are operating on and pipelining should work.

**Comment by jlautman** [comment]
Update: I see that by adding `identity-correction-for-post: true` to the readme, the regex is corrected to not include the trailing /regenerateKey.

Still, autorest should recognize that key management POST actions are operations on another resource, not nested resources. Get-AzSpoolKey should support the identity pipelining and the name parameter should honor --azure name simplification.

**Comment by jlautman** [comment]
@dolauli listkeys and regeneratekeys are POST actions on a resource. They should be able to be invoked in the context of that resource.

**Comment by dolauli** [comment]
@jlautman listkeys is designed as a post API is not because it is an action like regenerate. It is because keys are sensitive information. Implementing it as post instead of get is for security.

**Comment by jlautman** [comment]
@dolauli
The point that I'm making is that all POST actions on a resource need to be able to take the relevant resource as a pipeline parameter. Restart-AzSignalR and Restart-AzBatchComputeNode are both POST actions that take the target resource as a pipeline parameter. Would you argue that they are incorrect? Listkeys and Regeneratekey both require taking a target resource as a pipeline parameter for the same reasons why Restart commands do -- the action only makes sense in the context of the target resource.

Despite its name, Listkeys doesn't return a list. It returns a single object that has primary and secondary keys.

This is important because calling Listkeys using the expanded parameter set requires the resource group and resource name. Given a resource, there's no cmdlet that extracts the resource group. Therefore there's no easy way for a customer to get keys given the result from a resource GET.

Yes. We could write a custom cmdlet to implement Listkeys. However, listkeys is a very common pattern across Azure and should be supported by the generator by default.

I am asking that this issue be re-opened.

**Comment by dolauli** [comment]
My understanding is listkeys is designed as Post API is not because it is an action. If it is not list<keys> but list<some-none-sensitive-info>, it should be designed as get API, because this API does not include a request body, or change resource or resource status.

**Comment by jlautman** [comment]
> My understanding is listkeys is designed as Post API is not because it is an action. If it does not list<keys> but list<some-none-sensitive-info>, it should be designed as get API, because this API does not include a request body, or change resource or resource status.

@dolauli
If this information were not sensitive, it would be returned on the GET request to the resource as the resource has only one primary and secondary key. Resource GET does generate the ViaIdentity parameter set. Therefore this cmdlet should generate the ViaIdentity parameter set.

Key retrieval is always done in the context of the resource that the keys are properties of, much like a server restart is in the context of the server resource. The key retrieval cmdlet needs to be able to take that context as a parameter.

Keys are a property of a resource, not nested resources and should be retrievable in the same way other resource properties can be retrieved, using ViaIdentity.

Whether the Powershell cmdlets should generate the ListByParent parameter set (as that API is [required for all Azure Swaggers](https://github.com/Azure/azure-openapi-validator/blob/master/src/dotnet/OpenAPI.Validator/Validation/TrackedResourceListByImmediateParent.cs)) is a discussion for another day, as key retrieval is not a list by parent operation.

**Comment by dolauli** [comment]
@jlautman If you respect Restful, you may know that URL is mappped to resource instead of a resource property. So I think treating key here like a sub resource is acceptable. 
I am not saying your requirement is invalid. Right now, we are focusing on the required and most common features. And for your case, I think you may support it through customization for the time being. If we receive more relevant requirement from PM/developer/users, we may consider supporting it in the future.
Last, share another listkey with you https://github.com/Azure/azure-rest-api-specs/blob/master/specification/blockchain/resource-manager/Microsoft.Blockchain/preview/2018-06-01-preview/examples/BlockchainMembers_ListApiKeys.json.
As you could see from the example, unlike spool, it returns a list of keys.

**Comment by jlautman** [comment]
@dolauli I looked through the Azure documentation and it appears that there's a lot of inconsistency with listkeys endpoints, so you're right about that. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#list

That said, it looks like existing RPs on Az Powershell expect key post actions to work by pipeline.
Examples:
1. https://docs.microsoft.com/en-us/powershell/module/az.eventgrid/get-azeventgriddomainkey?view=azps-3.8.0
2. https://docs.microsoft.com/en-us/powershell/module/az.mixedreality/get-azspatialanchorsaccountkey?view=azps-3.8.0
3. https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/new-azcosmosdbaccountkey?view=azps-3.8.0
4. https://docs.microsoft.com/en-us/powershell/module/az.machinelearning/get-azmlwebservicekey?view=azps-3.8.0
5. https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/get-azoperationalinsightsworkspacesharedkey?view=azps-3.8.0

If you want all of these RPs to migrate to the new Az Powershell generator they're all going to ask for this behavior. Of note, these all also use `Name`, not `<resource>Name`, for the name parameter, so forcing them to use `<resource>Name` will be a major breaking change.

I'm simply asking that the special behavior for `<Resource>_Listkeys` is removed so that keys behave the same way as other POST actions. If an RP wants to have "list by parent" behavior they can always name the operation `Keys_ListBy<Resource>`.
