### ISSUE TITLE
ViaIdentity parameter set isn't generated for listkeys

### ISSUE THREAD

**Issue by jlautman** [Azure/autorest.powershell#589]
The listkeys cmdlet (`Get-Az<Resource>Key`) doesn't include a ViaIdentity parameter set. The regeneratekeys cmdlet (`New-Az<Resource>Key`) does. It should be possible to retrieve keys using the pipeline.

**Comment by jlautman** [comment]
Additionally, ViaIdentity parameter set isn't working for regeneratekeys despite it being generated. The error indicates that there is an issue with the URI composition.

**Comment by dolauli** [comment]
For get-xxx cmdlet, we will generate viaIdentity for getting a specific resource. And your case is actually a list operation, so we will not generate viaIdentity for it. It is by design, not a bug.
For regeneratekeys issue, add following configuration in the readme.md to fix it.
`identity-correction-for-post: true`

**Comment by jlautman** [comment]
Is there a way to get the ViaIdentity parameter set generated for `Get-Az<resource>Key`? This scenario seems like it should be valid.

`Get-Az<resource> | Get-Az<resource>Key`

**Comment by jlautman** [comment]
How do I apply the `identity-correction-for-post: true`? Is it applied using a directive? Is this correct?
```
  - where:
      subject: SpoolKey
      verb: New
    set:
      identity-correction-for-post: true
```

**Comment by dolauli** [comment]
> Is there a way to get the ViaIdentity parameter set generated for `Get-Az<resource>Key`? This scenario seems like it should be valid.
> 
> `Get-Az<resource> | Get-Az<resource>Key`

I think this scenario is something nice to support but not required.
Key here is actually treated as a sub resource of spool. For sub resource, we do not support to pipe in parent resource. For example, resource group is sub resource of subscription, and spool is sub resource of resource group, for get/update/remove-Azspool, we do not support to pipe in something like /subscriptions/xxx/resourceGroups/xxxx, and we just support to pipe in a spool identity.

And if you want to support it, you may customize based on the non viaIdentity parameter set.

**Comment by jlautman** [comment]
The keys are not sub resources of a spool resource. If the generator is treating the keys as sub resources then the generator is working incorrectly. Many Azure resources provide keys to access data plane sdks, and access to these keys needs to be accessible by the Powershell sdk. Is there a correct way to do this?

**Comment by jlautman** [comment]
@dolauli The existing model of treating keys as a nested resource is incorrect. POST actions are not nested resources -- they are actions on a resource. Not being able to take the acted upon resource in a pipeline is a major issue. How does the powershell generator handle other POST actions?

**Comment by jlautman** [comment]
@dolauli Despite "listkeys" having the name "list" in it, the operation is not a list operation. It's an action.

Under the current generation, I can do this:
`Get-AzSpool | New-AzSpoolKey -PrimaryKey`

But I can't do this
`Get-AzSpool | Get-AzSpoolKey`

Both of these are POST actions and should be treated the same.

**Comment by dolauli** [comment]
Same reason as issue#588
