### ISSUE TITLE
ViaIdentity generated extensions should not be case sensitive

### ISSUE THREAD

**Issue by jlautman** [Azure/autorest.powershell#596]
The generated ViaIdentity extensions that are used by the cmdlets are case sensitive, which breaks using the cmdlets in Dogfood.

Example:
```csharp
var _match = new global::System.Text.RegularExpressions.Regex("^/subscriptions/(?<subscriptionId>[^/]+)/resourceGroups/(?<resourceGroupName>[^/]+)/providers/Microsoft.SpoolService/spools/(?<spoolName>[^/]+)$").Match(viaIdentity);
```

When resource ids are returned from production, the RP namespace is capitalized as in the regex. However, dogfood returns the RP namespace in all lower case. This is causing the regex not to match.

The regex should be case insensitive as ARM uri groups (such as subscriptions, resourceGroups, providers, resource types, and the provider namespace) are case insensitive.

The calls to Regex should add the `RegexOptions.IgnoreCase` switch.

**Comment by dolauli** [comment]
@jlautman From https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md, I only noticed _"The resource group names and resource names should be matched case insensitively. That means, for example, if a user creates a resource in resource group "rG1", and then calls a read operation on "RG1", the same resource should be returned even though the casing differs."_ 
Do you know whether there is an official document somewhere to claim the full URI (https://<endpoint>/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}?api-version={api-version}) is case-insensitive.

**Comment by jlautman** [comment]
I'm not aware of such a document. That said, there's no reason why making the other parts of the URI case insensitive would hurt anything, and as I've discovered, ARM isn't necessarily consistent in how it returns the namespace. Making the regex case insensitive doesn't harm anything but it would handle this inconsistency between ARM environments.

This is important because piping the result of a Get-Az* into the corresponding Remove-Az* should work, and it does in production, but it doesn't work in dogfood.

**Comment by jlautman** [comment]
Ping @dolauli

**Comment by dolauli** [comment]
The issue has been fixed.
