### ISSUE TITLE
Problems with `-Isolated` in .\test-module.ps1

### ISSUE THREAD

**Issue by isra-fel** [Azure/autorest.powershell#600]
2 issues:

1. The name `Isolated` is wrong, because if you do **not** specify `-Isolated`, the tests are actually run in isolated mode. If you specify `-Isolated`, tests are run in current powershell context.
1. If you specify `-Isolated`, `.\test-module.ps1` will kill the powershell process after tests are run.
    - Root cause is in `test-modules.ps1`, `Invoke-Pester` is called with `-EnableExit` which means it will exit the powershell process after tests are run. This behavior should be valid only when in isolated mode. Need to wrap it in an if-else block.

**Comment by isra-fel** [comment]
Example of issue 2:
```
Tests completed in 2.05s
Tests Passed: 0, Failed: 4, Skipped: 0, Pending: 0, Inconclusive: 0
-------------Done-------------

[process exited with code 4]
```

**Comment by dolauli** [comment]
Fixed autorest.powershell v4.
