### ISSUE TITLE
Changing the Implementation of IEventListener.Signal

### ISSUE THREAD

**Issue by georgend** [Azure/autorest.powershell#601]
I would like to WriteDebug HttpRequests and Responses when the -Debug switch is specified on command execution. 
I was considering changing the implementation of IEventListener.Signal in each cmdlet, is this the right way to do it?
What extensibility points exist to hook into the pipeline and write out the desired information?

**Comment by dolauli** [comment]
You will need to implement the EventListener In the generated/Modules.cs.
