### ISSUE TITLE
[AzureStack] Get-AzLocation & Get-AzContext calls are not recorded during test - record mode

### ISSUE THREAD

**Issue by viananth** [Azure/autorest.powershell#605]
Autorest generated AzureStack admin module cmdlets make implicit calls to get location using Get-AzLocation and Get-AzContext. But during test recording, these calls are not getting recorded.

Example: https://github.com/Azure/azurestack-powershell/blob/pipeline/src/Azs.Gallery.Admin/test/Add-AzsGalleryItem.Recording.json

The above recording for Add-AzsGalleryItem should also contain http requests for Get-AzLocation.

**Comment by bganapa** [comment]
@dolauli Could you please update this issue with the progress or priority? This will be an issue for the azure modules as well. we neede not worry abount get-azcontext as it is not going to make any REST calls, but Get-AzLocation should be recorded.

**Comment by dolauli** [comment]
@viananth @bganapa 
To make recording and playback test work, you will need to pass following parameter to get-azlocation, because test relies on these two parameters to pass in the mock http handler to support recording.
`    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Databricks.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Databricks.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},`

**Comment by dolauli** [comment]
Please see generated\runtime\HttpPipelineMocking.ps1 in your generated code for how the recording test works. And following part is how the mock handler is attached to the http pipeline during testing.
```
# set the HttpPipelineAppend for all the cmdlets
$PSDefaultParameterValues["*:HttpPipelinePrepend"] = $Mock
```
