### ISSUE TITLE
[AzureStack] Piping throws error in CI pipeline

### ISSUE THREAD

**Issue by viananth** [Azure/autorest.powershell#606]
Piping scenario breaks during CI pipeline.
Test pipeline link: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1621&_a=summary

For example the “Remove-AzsGalleryItem” below will work if I run it on an env.
 
        Get-AzsGalleryItem -Name $name | Remove-AzsGalleryItem
 
But the same fails when run on the test pipeline with the error:
 

> [-] TestCreateAndDeleteGalleryItemPiped 115ms
>       ParameterBindingException: Cannot process command because of one or more missing mandatory parameters: Name. This error might have been caused by applying the default parameter binding. You can disable the default parameter binding in $PSDefaultParameterValues by setting $PSDefaultParameterValues["Disabled"] to be $true, and then trying again. The following default parameters were successfully bound for this cmdlet when the error occurred: -SubscriptionId -HttpPipelinePrepend
>       at <ScriptBlock>, D:\a\1\s\src\Azs.Gallery.Admin\test\Remove-AzsGalleryItem.Tests.ps1: line 26
 

As suggested by Xiaogang, we used -InputObject parameter to work around this issue. But this issue needs to be fixed.

**Comment by bganapa** [comment]
@dolauli We changed many of our tests to workaround this issue.  Could you please assign priority and provide a timeline? This is an issue for azure modules as well

**Comment by dolauli** [comment]
The workaround is actually a trade-off here. Otherwise, we have to disable $PSDefaultParameterValues as you could from the error message above, which means for each test, users have to specify those default parameter values.
