### ISSUE TITLE
Null-reference exception when response code is not defined

### ISSUE THREAD

**Issue by isra-fel** [Azure/autorest.powershell#613]
If server returns a code that is not defined in openapi spec, generated modules will not only throw an `UndeclaredResponseException` but also a null-reference exception.
![image](https://user-images.githubusercontent.com/11371776/84868493-5af51d00-b0af-11ea-83f3-2bbe0ea1e451.png)

Cause:
https://github.com/Azure/azure-powershell/blob/master/src/MySql/generated/runtime/UndeclaredResponseException.cs#L46

```diff
- json = json.Property("error") ?? json;
+ json = json?.Property("error") ?? json;
```

**Comment by dolauli** [comment]
This code is not generated and shared across all the generated module. And you should find it in  powershell/resources/runtime/csharp/client/UndeclaredResponseException.cs.
