### ISSUE TITLE
Expose a knob to retry on common network related errors on the client side

### ISSUE THREAD

**Issue by bganapa** [Azure/autorest.powershell#614]
For along running operation, when the client side polls for the results, it may encounter netowrk related encounter on the client side for various reasons. The generated cmdlet should have the capability to retry automatically on network related errors, instead of stopping abruptly

We have this kind of retries in the older Auzrestack admin modules and we dont want to lose that capability with the autorest generator move

**Comment by dolauli** [comment]
Link the [discussion ](https://github.com/Azure/autorest.powershell/issues/527) here.

**Comment by dolauli** [comment]
Fixed in autorest.powershell v4. Fixed in https://github.com/Azure/autorest.powershell/pull/1150.
