### ISSUE TITLE
Issues with empty objects in OpenAPI spec

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/autorest.powershell#668]
I have a couple "Free-Form Objects" [like so](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/stable/2019-12-12/HybridCompute.json#L1097-L1100):
```jsonc
{
  "MachineExtensionProperties": {
    "properties": {
      "settings": {
        "type": "object",
        "description": "Json formatted public settings for the extension."
      }
    }
    // ...
  }
  // ...
}
```

These should be represented as "Free-Form Objects" as defined here: https://swagger.io/docs/specification/data-models/data-types/#object

This gets generated into a type: `Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.Api201912.MachineExtensionPropertiesSettings`

and is accepted in the `Set-AzConnectedMachineExtension`'s `-Settings` parameter that I'm generating.

The closest thing in PowerShell for this concept is a hashtable so I tried passing in a hashtable into that setting param:

```pwsh
Set-AzConnectedMachineExtension -Settings @{ commandToExecute = "dir" }
```

debugging this cmdlet... the `Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.Api201912.MachineExtensionPropertiesSettings` that gets created is empty...

So I tried using the type directly:

```pwsh
$a = [Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.Api201912.MachineExtensionPropertiesSettings]::DeserializeFromDictionary(@{
   commandToExecute = "dir"
})
$a.ToJsonString()
```
```pwsh
$a = [Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.Api201912.MachineExtensionPropertiesSettings]::DeserializeFromPSObject([psobject]@{
   commandToExecute = "dir"
})
$a.ToJsonString()
```
both gives me:
```
{
}
```

Is it possible to use this type like a property bag? Is there anyway to get around this unexpected behavior?

**Comment by brianwp3000** [comment]
Pinging the thread because I just ran into this issue as well while attempting to generate a Powershell client for the Azure PlayFab SDK--this issue makes it impossible to use APIs that depend on being able to send arbitrary property bags in the request body.
Is there any workaround?

**Comment by dolauli** [comment]
Add `additionalproperties: true` should work around the issue.
```
{
  "MachineExtensionProperties": {
    "properties": {
      "settings": {
        "type": "object",
        "additionalProperties": true,
        "description": "Json formatted public settings for the extension."
      }
    }
    // ...
  }
  // ...
}
```
