### ISSUE TITLE
How do I hide a helper function from being exported? - DoNotExportAttribute not found

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/autorest.powershell#672]
I saw this:

- `Microsoft.Azure.PowerShell.Cmdlets.Aks.Models.DoNotExportAttribute`
  - Used in C# and script cmdlets to suppress creating an exported cmdlet at build-time. These cmdlets will *not be exposed* by `Az.Aks`.
- `Microsoft.Azure.PowerShell.Cmdlets.Aks.Models.InternalExportAttribute`
  - Used in C# cmdlets to route exported cmdlets to the `..\internal`, which are *not exposed* by `Az.Aks`. For more information, see [readme.md](..\internal/readme.md) in the `..\internal` folder.

and tried using the first on a helper function:

```pwsh
filter HandleShowResult {
    [Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.DoNotExport]
    [CmdletBinding()]
    param (
        [Parameter(Mandatory, ValueFromPipeline)]
        [string]
        $ShowResult,

        [Parameter(Mandatory)]
        [string]
        $ResourceGroupName,

        [Parameter(Mandatory)]
        [string]
        $SubscriptionId
    )

    # Get name of machine registered
    $selectStrResult = $ShowResult | Select-String -Pattern "^Resource Name\s+:(?<resourceName>.*)\n"
    $Name = $selectStrResult.Matches.Groups |
        Where-Object Name -EQ resourceName |
        Select-Object -ExpandProperty Value

    # Return the ConnectedMachine object.
    Get-AzConnectedMachine -Name $Name -ResourceGroupName $ResourceGroupName -SubscriptionId $SubscriptionId
}

<#
.Synopsis
API to register a new machine and thereby create a tracked resource in ARM
.Description
API to register a new machine and thereby create a tracked resource in ARM

.Link
https://docs.microsoft.com/powershell/module/az.connectedmachine/new-azconnectedmachine
#>
function New-AzConnectedMachine {
...
```

But it just gave me:

```
Get-ScriptCmdlet: /Users/tyleonha/Code/PowerShell/azure-powershell/src/ConnectedMachine/custom/Az.ConnectedMachine.custom.psm1:16
Line |
  16 |  … ember -Function (Get-ScriptCmdlet -ScriptFolder $PSScriptRoot) -Alias …
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find the type for custom attribute 'Microsoft.Azure.PowerShell.Cmdlets.ConnectedMachine.Models.DoNotExport'. Make sure that the assembly that contains this type is loaded.
```

Am I using this incorrectly? Do I need to import some module?

**Comment by dolauli** [comment]
I am thinking we may adding a **help** folder in the custom folder. And for cmdlets in these, we hide them when generating help and exports.

**Comment by isra-fel** [comment]
@TylerLeonhardt Hi Tyler, sorry for late response 😅 for your specific question, the answer is the namespace of `DoNotExportAttribute` was wrong in the docs. The real one should be `Microsoft.Azure.PowerShell.Cmdlets.{YourRP}` (without `Models`. Here's a working example:

```powershell
function HelloWorld {
    [Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.DoNotExport()] # can't omit ()
    [CmdletBinding()]
    param ()
}
```

I'll correct the docs and discuss other possibly better solutions of hiding some logic from being exported.

**Comment by isra-fel** [comment]
Plus, functions are not exported unless they have `CmdeltBinding` attrubte
