### ISSUE TITLE
metadata not populating licenseUrl and projectUrl in nuspec file

### ISSUE THREAD

**Issue by topherrr** [Azure/autorest.powershell#678]
Metadata values like authors, companyName, copyright, etc... specified in my readme.md populate properly in my nuspec/psd1's but licenseUrl and projectUrl do not. This obviously causes build-module -pack to fail. 

I'm using latest.

**Comment by dolauli** [comment]
I can not reproduce the issue.
Please see https://github.com/Azure/azure-powershell/blob/generation/src/readme.azure.noprofile.md for a common readme.md we are using in azure powershell.  And see https://github.com/Azure/azure-powershell/tree/generation/src/Databricks for a sample,  in which if you run autorest, you should see licenseUrl and projectUrl are correctly populated.

**Comment by topherrr** [comment]
Thanks, my issue was projectUr[i] not projectUr[l] in metadata section.
