### ISSUE TITLE
Perf concerns with AliasesToExport = '*' in module manifest (.psd1)

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#687]
## Problem
When a module doesn't have an alias to export, AutoREST generates the module manifest with `AliasesToExport = '*' `. This causes perf issues in PowerShell when a module has a lot of commands.
``` ps
# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'
```

## Ask
If a module doesn't have an alias to export, AutoREST should set its `AliasesToExport` to an empty array `@()` i.e. `AliasesToExport = @()`.

Ref: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/269

**Comment by dolauli** [comment]
Fixed in v4.
