### ISSUE TITLE
build-module.ps1 failure for AzureStack module

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/autorest.powershell#688]
With autorest installed from npm with “install -g autorest”, one of our AzureStack modules, Azs.AzureBridge.Admin, failed during build-module.ps1 with this error:

generated\api\Models\Api201601\ExtendedProductProperties.cs(72,121): error CS0539: 'ExtendedProductProperties.Version1' in explicit interface declaration is not found among members of the interface that can be implemented [D:\a\1\s\src\Azs.AzureBridge.Admin\Azs.Azurebridge.Admin.csproj] 
generated\api\Models\Api201601\ExtendedProductProperties.cs(8,9): error CS0535: 'ExtendedProductProperties' does not implement interface member 'IVirtualMachineProductPropertiesInternal.Version.set' [D:\a\1\s\src\Azs.AzureBridge.Admin\Azs.Azurebridge.Admin.csproj] 
Write-Error: D:\a\1\s\src\Azs.AzureBridge.Admin\build-module.ps1:85 
Line | 
85 | Write-Error 'Compilation failed.' 
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
| Compilation failed. 

Here is the pipeline failure:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=525687&view=logs&j=6399d89d-3d30-5fff-3e92-07bbaf7ebe2f&t=338dbded-3565-55f6-8a6d-e0877585a459

**Comment by dolauli** [comment]
Fixed
