### ISSUE TITLE
[PowerShell] Generated code fails to build due to warnings

### ISSUE THREAD

**Issue by asundheim** [Azure/autorest.powershell#693]
After generating a PowerShell module, in almost every generated C# file, there are warnings such as:

`warning CS1570: XML comment has badly formed XML -- '"'`

`warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.'`

` warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.`

` warning CS1574: XML comment has cref attribute 'className' that could not be resolved`

`warning CS1591: Missing XML comment for publicly visible type or member 'CreatedByType.Application'`

` warning CS1587: XML comment is not placed on a valid language element`

---
Attempting to run `build-module.ps1`  inevitably fails since the `.csproj` has `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`

---
autorest flags used: `--powershell`
config: `openapi-type: arm`

**Comment by dolauli** [comment]
@asundheim Would you give more details as below?
- The swagger file
- how do you run autorest?

**Comment by asundheim** [comment]
@dolauli this was asked by the Az Lab Services / DTL team, they'll have those answers.

**Comment by dolauli** [comment]
Close it since there is no further update from the reporter.
