### ISSUE TITLE
POST /listKeys is generated with -WhatIf and -Confirm

### ISSUE THREAD

**Issue by isra-fel** [Azure/autorest.powershell#704]
## Problem

Many services have this API `POST /.../listKeys` to list keys that can be used to access some resources. Autorest.powershell generates them as `Get-*Keys` cmdlets (which is as expected) but with `-WhatIf` and `-Confirm` (which is not).

## Expected behavior
Because `listKeys` does not change state on Azure, we should not generate `-WhatIf` and `-Confirm`

Example swagger: https://github.com/Azure/azure-rest-api-specs/blob/9abfdcfef776c1402cbd53855275b9bc17eb52ab/specification/redisenterprise/resource-manager/Microsoft.Cache/preview/2020-10-01-preview/redisenterprise.json#L672

**Comment by isra-fel** [comment]
According to [this comment](https://github.com/Azure/azure-rest-api-specs/issues/8335#issuecomment-684253276) , listKeys APIs are designed to be POST for security reasons - POST requires higher permission and keys are sensitive data that they want to protect them with higher permission.

As for PowerShell, the requirement remains valid -- it does not change any state on Azure, so it should not have `-WhatIf` and `-Confirm`. I think we should handle it as a special exception.

**Comment by isra-fel** [comment]
Need to set writeable https://github.com/Azure/autorest.powershell/blob/master/powershell/generators/script-cmdlet.ts#L29 to false, so that the generated cmdlet will not support shouldprocess

**Comment by isra-fel** [comment]
Another common case is `POST /checkNameAvailability`: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json#L65

**Comment by dolauli** [comment]
Fixed in autorest.powershell v4.
