### ISSUE TITLE
Directives- new support

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#715]
Add support to changing parameters from Mandatory/Required to not mandatory/not required and vice versa.

**Comment by dolauli** [comment]
Whether a parameter is required or optional should be defined in swagger. If swagger is incorrect, you may correct it through the **transform** directive.
See https://github.com/Azure/autorest/blob/6ad8958b65506899b3889a1606e39f1c2d17cc79/Samples/openapi-v2/3b-custom-transformations/generated/configuration.yaml for details.
