### ISSUE TITLE
Optional parameter child required property should not be generated as required parameter of new-* cmdlet

### ISSUE THREAD

**Issue by blueww** [Azure/autorest.powershell#719]
#### Swagger:
- "username" and "password" are required for object "[IscsiTargetCredentials](https://github.com/Azure/azure-rest-api-specs/blob/71b0e8e804a77598d47aef72decebe261bc7f871/specification/storagepool/resource-manager/Microsoft.StoragePool/preview/2020-03-15-preview/storagepool.json#L1213)"
- "IscsiTargetCredentials" is optional in "[Acl](https://github.com/Azure/azure-rest-api-specs/blob/71b0e8e804a77598d47aef72decebe261bc7f871/specification/storagepool/resource-manager/Microsoft.StoragePool/preview/2020-03-15-preview/storagepool.json#L1160)"

So "username" and "password" should be actually optional in "Acl"

#### generated code
Run following command to generate a cmdlet that will create "Acl" object, 
`New-InMemoryObjectScriptCreator -CsPath .\generated\api\Models\Api20200315Preview\Acl.cs -OutputDir ./custom -ModuleName DiskPool `
The generated cmdlet will have "CredentialsUsername" and "CredentialsPassword" as required, but they are actually optional.
```powershell
New-AzDiskPoolAclObject -CredentialsPassword <String> -CredentialsUsername <String> -InitiatorIqn <String> -MappedLun <String[]> [<CommonParameters>]
```

**Comment by dolauli** [comment]
Fixed in 3.0.411.
