### ISSUE TITLE
Optional parameter in AllOf

### ISSUE THREAD

**Issue by wyunchi-ms** [Azure/autorest.powershell#729]
In [`CostManager`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json) `from` is come from [`ExportProperties`](https://github.com/Azure/azure-rest-api-specs/blob/5d3716e02a81cfb2c89187ce282bcaffd5785956/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json#L768)->[`CommonExportProperties`](https://github.com/Azure/azure-rest-api-specs/blob/5d3716e02a81cfb2c89187ce282bcaffd5785956/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json#L783)->[`ExportDefinition`](https://github.com/Azure/azure-rest-api-specs/blob/5d3716e02a81cfb2c89187ce282bcaffd5785956/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json#L912)->[`ExportTimePeriod`](https://github.com/Azure/azure-rest-api-specs/blob/5d3716e02a81cfb2c89187ce282bcaffd5785956/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json#L993)->[`from`](https://github.com/Azure/azure-rest-api-specs/blob/5d3716e02a81cfb2c89187ce282bcaffd5785956/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01/costmanagement.exports.json#L1009). But it's optional in `CommonExportProperties` but required in `ExportProperties`.

**Comment by dolauli** [comment]
Fixed in 3.0.416
