### ISSUE TITLE
Cannot using autorest version 3.0 or higher to generate Code that handles the 200 status code correctly.

### ISSUE THREAD

**Issue by Youri970410** [Azure/autorest.powershell#733]
- In Swagger,the definition of the status code "200" in the responses to the url "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices/{cloudServiceName}/roleInstances/{roleInstanceName}/remoteDesktopFile" shows that we need to export a parameter "path" to download file:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/preview/2020-10-01-preview/cloudService.json
- In autorest version 2.x.x,it can be generated successfully,but it cannot be generated correctly in versions above 3.0.

**Comment by dolauli** [comment]
Fixed in 3.0.417
