### ISSUE TITLE
Support PowerShell Positional Parameters

### ISSUE THREAD

**Issue by danielniccoli** [Azure/autorest.powershell#749]
AutoRest should support the definition of positional parameters.

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/types-of-cmdlet-parameters?view=powershell-7

**Comment by Borkason** [comment]
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/213 depends on the implementation of this feature.

**Comment by isra-fel** [comment]
Duplicate, we will track it in https://github.com/Azure/autorest.powershell/issues/297
