### ISSUE TITLE
Under what conditions would a variant change?

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#752]
Given that variants are used by rename directives to uniquely identify a cmdlet to rename, how do you ensure that variants remain the same even as new paths are added to an OpenAPI document? 

We recently encountered a case where a variant changed from `Get` to `Get1`. This threw off our rename directives and the rename was done to the wrong cmdlet. Is there a more permanent\idempotent way to alter generated cmdlets, or ensure that variant names don't change even as new API paths are added to an OpenAPI document?

Also, under what conditions would a variant change except for the removal of a path in an OpenAPI document?

**Comment by dolauli** [comment]
Would you give more details about how this happens?

**Comment by dolauli** [comment]
And generally speaking, there should be not Get1 variant. If it happens, it normally means there is operationId which should be named xxx-listxxx but is wrong named xxx-getxxx. (for resource list, the verb list should be used instead of get) @peombwa
