### ISSUE TITLE
Duplicate parameter  and partial method

### ISSUE THREAD

**Issue by Agazoth** [Azure/autorest.powershell#776]
I'm working on this swagger: [Partnercenter Insights](https://api.partnercenter.microsoft.com/insights/v1/mpn/swagger/v1/swagger.json)

The clean swagger is here: [s.txt](https://github.com/Azure/autorest.powershell/files/6604598/s.txt)

The json contains identical tags on paths, but fixing those makes it possible to generate autorest for csharp without errors. Running autorest for PowerShell causes some issues, though.

Opening the generated files in VS Code reviles the following errors:
 
![image](https://user-images.githubusercontent.com/15127301/120934253-deaf7b80-c6fd-11eb-8649-34fce7e72826.png)

What would be the best way to proceed to rat out the errors?

**Comment by dolauli** [comment]
There should be a property called operationId for each API. Please refer to https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json#L42 for an example
