### ISSUE TITLE
Get-Az{} supports to pipe in parent object

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/autorest.powershell#781]
Currently pipe operation requires input object should be the same type. It is inconvenient when user wants to list all child resources under one parent resource. Please consider to support it.

For instance
```
Get-AzParentResource -ResourceGroupName <> -Name <> | Get-AzChildResource
```

**Comment by dingmeng-xue** [comment]
Besides parent-child relation, how can we support easy customization approach? Below is requirement from WVD customer

> An example: Get-AzWvdHostpool | Out-Gridview -OutputMode Single | Get-AzWvdSessionhost
This returns an error
Another example: Get-AzWvdApplicationGroup | Out-Gridview -OutputMode Single | Get-AzWvdDesktop

**Comment by blueww** [comment]
This might should apply to not only Get-* cmdlet, but also New-* cmdlet.

**Comment by VeryEarly** [comment]
implemented: https://github.com/Azure/autorest.powershell/pull/1116
