### ISSUE TITLE
Support Customization for Enum Values

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/autorest.powershell#784]
We found some enum values are not a single word but a phase. But in PowerShell, it is better const values could be a single word. Following is some examples in swagger.

Following is an example from the swagger of AppConfiguration. As we can see the enum value in bold is a phase instead of a single word. In Azure PowerShell, we should map it to a single word to make it convenient for users to use it.
```
 "ResourceIdentity": {
      "type": "object",
      "description": "An identity that can be associated with a resource.",
      "properties": {
        "type": {
          "description": "The type of managed identity used. The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user-assigned identities. The type 'None' will remove any identities.",
          "enum": [
            "None",
            "SystemAssigned",
            "UserAssigned",
            "SystemAssigned, UserAssigned"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "IdentityType",
            "modelAsString": true
          }
        },
```

**Comment by dolauli** [comment]
The reason we need to add this is because sometimes enum value is not a single word but something like "xxx yyy". To support completer, we will have change it to a single word like xxxoryyy. Another solution is to have the value in a pair of single quotes. And  we take the second solution.
