### ISSUE TITLE
Expected Example Format

### ISSUE THREAD

**Issue by georgend** [Azure/autorest.powershell#791]
Current AutoRest.PowerShell expects Examples to have the following format:-
````
### Example 1: {{ Add title here }}
```powershell
PS C:\> {{ Add code here }}

{{ Add output here }}
```

{{ Add description here }}

### Example 2: {{ Add title here }}
```powershell
PS C:\> {{ Add code here }}

{{ Add output here }}
```

{{ Add description here }}

````
When this format is not followed a fatal exception that crashes the Code Generation process is thrown as referenced in #790.

According to guidance provided to [content developers](https://docs.microsoft.com/en-us/powershell/scripting/community/contributing/editorial-checklist?view=powershell-7.1#cmdlet-reference-examples) and platyps the format should be as follows:-
````
### Example X – title

0 or more paragraphs

1 or more code blocks

0 or more paragraphs.

````
Or 
````
### Example 1 - Descriptive title

Zero or more short descriptive paragraphs explaining the context of the example followed by one or
more code blocks. Recommend at least one and no more than two.

```powershell
... one or more PowerShell code statements ...
```

```Output
Example output of the code above.
```

Zero or more optional follow up paragraphs that explain the details of the code and output.
````

Is it possible for AutoRest.PowerShell to support the standard/convention established in the editorial checklist as well as platyps standard?

cc. @sdwheeler, @msewaweru, @mairissi, @peombwa

**Comment by dolauli** [comment]
All Azure PowerShell modules' examples are based on this format so we can not make this change. This format is more strict and compatible with platyPS.
Please see https://github.com/Azure/azure-powershell/blob/main/src/Databricks/examples/Get-AzDatabricksWorkspace.md for a sample example. And you may click https://docs.microsoft.com/en-us/powershell/module/az.databricks/get-azdatabricksworkspace?view=azps-6.0.0 to see what it shows in Microsoft docs.
