### ISSUE TITLE
License Text Duplicated in ProxyCmdletDefinition.ps1

### ISSUE THREAD

**Issue by georgend** [Azure/autorest.powershell#814]
The License header emitted into ProxyCmdletDefinition.ps1 by `[Export-ProxyCmdlet`](https://github.com/Azure/autorest.powershell/blob/59e8eb2020d0f70fabd5ef0cc203996b4d818f63/powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs#L86-L99) is duplicated for each cmdlet. Generating unnecessary bloat in the resulting Nuget Package and ProxyCmdletDefinition.ps1 file.

It would be ideal if only one license instance was present at the head of the file.

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/824

**Comment by maisarissi** [comment]
Hi @dolauli .
Can this fix be applied to the msgraph branch as well? Otherwise we will remain with this issue.
Thanks!
