### ISSUE TITLE
Extend `--license-header` to cover the generated ProxyCmdletDefinition.ps1

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#817]
Currently, `--license-header` only applies the specified license header to `.cs` cmdlets under `/generated/cmdlets/`. In relation to #814, `--license-header` should also be extended to also set the provided license-header in `ProxyCmdletDefinition.ps1`.

### Repro Steps
1. Run `autorest --powershell --license-header:MICROSOFT_MIT_NO_VERSION --input-file:{ANY_FILE}`  with any input file.
2. Inspect the generated module.
    - Only `.cs` files will have the specified license header.
    - Scripts under `/generated/exports/` will have a hardcoded Apache license header - https://github.com/Azure/autorest.powershell/blob/59e8eb2020d0f70fabd5ef0cc203996b4d818f63/powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs#L86-L99

#### Environment
``` powershell
AutoRest core: 3.0.6306
AutoRest PowerShell: 2.1.402
```

### Expected behavior
Scripts under `/generated/exports/`, including `ProxyCmdletDefinition.ps1`, should have the same license header as `.cs` files in `/generated/cmdlets/` when `--license-header:MICROSOFT_MIT_NO_VERSION` is specified.

**Comment by dolauli** [comment]
Add --pwsh-license-header to set license header for generated powershell code.
If --pwsh-license-header is not set, --license-header is applied.
And magic words for this setting include:

microsoft_mit_no_version
microsoft_apache_no_version
microsoft_apache_no_codegen
microsoft_mit_small_no_codegen
