### ISSUE TITLE
Notes need be removed now

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/autorest.powershell#832]
https://docs.microsoft.com/en-us/powershell/module/az.addomainservices/get-azaddomainservice?view=azps-6.4.0#notes
![image](https://user-images.githubusercontent.com/19869716/132806128-83a43b27-dbac-4f0c-8690-944ced92f623.png)

We have documentation for input and output type in autorest-based module. The notes should be removed

**Comment by dingmeng-xue** [comment]
We need to ask other partner's and consider it is a breaking change.

**Comment by BethanyZhou** [comment]
Close as finished.
