### ISSUE TITLE
ErrorActionPreference is not respected

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/autorest.powershell#846]
test.ps1 contains below sample scripts
```
$ErrorActionPreference = "Stop"
Get-AzDatabricksWorkspace -Name SomethingThatNotExists -ResourceGroupName NotExistsAsWell
Write-Host "The script is still running"
```

The script execution doesn't respect the setting of `$ErrorActionPreference`. The output is
```
PS C:\Dev> .\test.ps1
Get-AzDatabricksWorkspace_Get: C:\Dev\test.ps1:2
Line |
   2 |  Get-AzDatabricksWorkspace -Name SomethingThatNotExists -ResourceGroup …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Resource group 'NotExistsAsWell' could not be found.

The script is still running
PS C:\Dev> $ErrorActionPreference
Continue
```

The expected result is that scripts after `Get-AzDatabricksWorkspace` should not be executed because of `$ErrorActionPreference = "Stop"`

**Comment by dolauli** [comment]
In the design of autorest.powershell, we finally export script-module functions to users.  But for powershell, they have a limitation for functions in script modules, that is there is no way to honor the caller's preference-variable values / inherited common parameters in functions defined in script modules. And for this case, the workaround is to use `-ErrorAction` common parameter.

Please see https://github.com/PowerShell/PowerShell/issues/4568 and https://stackoverflow.com/questions/55839607/is-it-possible-to-configure-erroractionpreference-stop-as-the-default-for-a for more details.

Currently there is nothing we can do about the issue except for the workaround.

**Comment by dolauli** [comment]
In interactive, it is OK. You need to put them in a script to reproduce the issue.
