### ISSUE TITLE
Treat all `2xx` status codes as success

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#853]
The generated commands should treat all 2xx HTTP status codes as success, or we should provide an option to specify this behavior via a configuration. With Microsoft Graph API, treating all 2xx status codes as success is generally recommended since some APIs can return any status code in the 2xx range to mean success. e.g., [Security APIs](https://docs.microsoft.com/en-us/graph/api/alert-list?view=graph-rest-1.0&tabs=http#response) can return `200` or `206` depending on response from the provider.

The OpenAPI files may not always contain all status codes in the response object.

### Potential solution
Instead of handling each status code in a switch, we should check if the response message [`IsSuccessStatusCode`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.issuccessstatuscode?view=net-5.0) and call an `onSuccess` callback method.

#### Instead of this (before)
``` cs
switch (_response.StatusCode)
{
    case global::System.Net.HttpStatusCode.OK:
        {
            await eventListener.Signal(Microsoft.Graph.PowerShell.Runtime.Events.BeforeResponseDispatch, _response); if (eventListener.Token.IsCancellationRequested) { return; }
            await onOk(_response, _response.Content.ReadAsStringAsync().ContinueWith(body => Microsoft.Graph.PowerShell.Models.CollectionOfAlert.FromJson(Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(body.Result))));
            break;
        }
    default:
        {
            await eventListener.Signal(Microsoft.Graph.PowerShell.Runtime.Events.BeforeResponseDispatch, _response); if (eventListener.Token.IsCancellationRequested) { return; }
            await onDefault(_response, _response.Content.ReadAsStringAsync().ContinueWith(body => Microsoft.Graph.PowerShell.Models.OdataError.FromJson(Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(body.Result))));
            break;
        }
}
```

#### Lets to do this (Suggested change)
``` cs
if (_response.IsSuccessStatusCode)
{
    await eventListener.Signal(Microsoft.Graph.PowerShell.Runtime.Events.BeforeResponseDispatch, _response); if (eventListener.Token.IsCancellationRequested) { return; }
    // We can then handle specific status code in the onSuccess call back if need be.
    // We should also deserialize the content based on the response schema of a 2xx status code in the OpenAPI file. 
    await onSuccess(_response, _response.Content.ReadAsStringAsync().ContinueWith(body => Microsoft.Graph.PowerShell.Models.CollectionOfAlert.FromJson(Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(body.Result))));
} else
{
    await eventListener.Signal(Microsoft.Graph.PowerShell.Runtime.Events.BeforeResponseDispatch, _response); if (eventListener.Token.IsCancellationRequested) { return; }
    await onDefault(_response, _response.Content.ReadAsStringAsync().ContinueWith(body => Microsoft.Graph.PowerShell.Models.OdataError.FromJson(Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(body.Result))));
}
```

**Comment by dolauli** [comment]
We have handled different 2XX if you have defined them in swagger.
For example, if you define following responses as
```
        "responses": {
          "200": {
            "description": "OK - Returns the workspace.",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "206": {
            "description": "OK - Returns the workspace.",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "204": {
            "description": "OK - Returns the workspace."
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
``` 
We will generate code as below.
```
                    switch ( _response.StatusCode )
                    {
                        case global::System.Net.HttpStatusCode.OK:
                        {
                            await eventListener.Signal(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Events.BeforeResponseDispatch, _response); if( eventListener.Token.IsCancellationRequested ) { return; }
                            await onOk(_response,_response.Content.ReadAsStringAsync().ContinueWith( body => Microsoft.Azure.PowerShell.Cmdlets.Databricks.Models.Api20180401.Workspace.FromJson(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Json.JsonNode.Parse(body.Result)) ));
                            break;
                        }
                        case global::System.Net.HttpStatusCode.NoContent:
                        {
                            await eventListener.Signal(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Events.BeforeResponseDispatch, _response); if( eventListener.Token.IsCancellationRequested ) { return; }
                            await onNoContent(_response);
                            break;
                        }
                        case global::System.Net.HttpStatusCode.PartialContent:
                        {
                            await eventListener.Signal(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Events.BeforeResponseDispatch, _response); if( eventListener.Token.IsCancellationRequested ) { return; }
                            await onPartialContent(_response,_response.Content.ReadAsStringAsync().ContinueWith( body => Microsoft.Azure.PowerShell.Cmdlets.Databricks.Models.Api20180401.Workspace.FromJson(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Json.JsonNode.Parse(body.Result)) ));
                            break;
                        }
                        default:
                        {
                            await eventListener.Signal(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Events.BeforeResponseDispatch, _response); if( eventListener.Token.IsCancellationRequested ) { return; }
                            await onDefault(_response,_response.Content.ReadAsStringAsync().ContinueWith( body => Microsoft.Azure.PowerShell.Cmdlets.Databricks.Models.Api20180401.ErrorResponse.FromJson(Microsoft.Azure.PowerShell.Cmdlets.Databricks.Runtime.Json.JsonNode.Parse(body.Result)) ));
                            break;
                        }
                    }
```

**Comment by dolauli** [comment]
@peombwa @darrelmiller Share some of my points.

- For 4xx responses,  I agree that we should not list all of them in the swagger.  And errors normally share the same schema of response, and a good place for them is the **default**. But for 2xx responses, I do think we should list all of them in the schema. And there are two reasons for this.
  - Firstly, from service side, I do not think there should be some unknown 2xx responses in advance.
  - Secondly, Different responses of 2xx normally do not share the same schema of response. For your case, if 206 is not defined in swagger, How could we generate response model for 206, since there is no response schema defined for 206.

**Comment by darrelmiller** [comment]
@dolauli   The HTTP specification is very clear on what a client MUST do.  The OpenAPI specification is in agreement.  

201 and 200 can often return the same schema. The content-length header will tell the client if there is a payload for the 201.  If there is the shape will likely be the same as 200.  203 is not something an API provider may know about and therefore would not likely ever be listed in the OpenAPI description.  204 has a well defined empty response payload which a client can return a null value.  Same for 205.

In this case of a 206 the same response payload for 200 will work just fine. 207 responses are likely going to be the same shape as a 200, the only difference being the inclusion of some error messages in the payload.  I've never seen anyone use 208 or 226.

Failing because of an unexpected status code is wrong according to HTTP and OpenAPI.

**Comment by darrelmiller** [comment]
@dolauli Agreed. If we have `default` in our OpenAPI then you are doing the right thing.  We should fix our OpenAPI.  I'm assuming that even if we remove the default you would still throw an error.

We will find another way to resolve this in the meanwhile.  We would really appreciate if you could add supporting 2XX to your backlog.
