### ISSUE TITLE
Request JSON has "auth.type=" while auth type is not specified

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/autorest.powershell#858]
## Basic information
Module: WebPubSub (now merged to SignalR )
Command: New-AzWebPubSubHub
Parameter: EventHandler

When the event handler hash map doesn't contain an "AuthType" key, the actual request body has an "auto.type=" field, which makes the command fail. The auth type is not a required property of event handler.

## Reproduce
```powershell
$eventHandler = @{UrlTemplate = 'http://example.com/api/{hub}/connect/{event}' ;  }

New-AzWebPubSubHub -Name testHub -ResourceGroupName psdemo -ResourceName psdemo-wps -EventHandler $eventHandler  
```

Output:  New-AzWebPubSubHub_CreateExpanded: Invalid arguments

Request body:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15143836/139428211-9760bac8-c307-4e84-8310-f4ad9b73c31e.png)

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/autorest.powershell/pull/865

**Comment by Y-Sindo** [comment]
@dolauli I'd like to ask when the fix will be release?

**Comment by dolauli** [comment]
It has been released. To get the autorest.powershell with this fix, you need to run `autorest --reset`
