### ISSUE TITLE
Cannot build PowerShell module

### ISSUE THREAD

**Issue by DomLennonZA** [Azure/autorest.powershell#859]
Hi,

When attempting to run `.\generated\build-module.ps1 -Run` I get the following exceptions:

`error CS1056: Unexpected character '$'`
and
`error CS1525: Invalid expression term ''`

It seems that the C# being generated is invalid. Please see the attached screenshot for an example.
![image](https://user-images.githubusercontent.com/2950221/139847821-2ae77af6-4a64-4149-b48c-85cb985fbea3.png)

The command used to run this is `autorest --powershell --input-file:./swagger.json`

I'm unsure if what I am doing is incorrect, but this seems to be a bug.

Thanks,
Dom

**Comment by dolauli** [comment]
@DomLennonZA  Would you post your swagger file?

**Comment by dolauli** [comment]
@DomLennonZA Any update?

**Comment by dolauli** [comment]
Close since no further feedback from the reporter.
