### ISSUE TITLE
License Text Duplicated in ProxyCmdletDefinition.ps1

### ISSUE THREAD

**Issue by maisarissi** [Azure/autorest.powershell#873]
Related to https://github.com/Azure/autorest.powershell/issues/814.

The "license text" remains duplicated when generating Microsoft Graph PowerShell SDK because the fix wasn't merge into the msgraph branch.

@dolauli @dingmeng-xue please, merge the fix into msgraph branch as well.

**Comment by dolauli** [comment]
@georgend has done it in PR https://github.com/Azure/autorest.powershell/pull/874. And I have merged it.
