### ISSUE TITLE
With Produces 'text/plain' and response schema type of integer, OutputType becomes bool

### ISSUE THREAD

**Issue by ThePoShWolf** [Azure/autorest.powershell#892]
I'm working with an API endpoint with the following relevant details:

```json
    "paths": {
      "/api/v2/resource/count": {
        "get": {
          "tags": [
            "Resource"
          ],
          "operationId": "Resource_Count",
          "produces": [
            "text/plain"
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "type": "integer"
              }
            }
          }
        }
      }
```

This produces a cmdlet that has an output type of `bool`, which is unexpected and doesn't actually return the data that the API is sending. Here's the line from the .cs file:

```csharp
[global::System.Management.Automation.OutputType(typeof(bool))]
```

If I switch the produces to be `application/json`, then autorest will produce a cmdlet with an `int` output type. However, the API is returning a plaintext integer, so the cmdlet throws an error. While I do expect the API will be updated to JSON encode the response, it is still a weird issue.

**Comment by dolauli** [comment]
We have no plan to support 'plain/text'. Actually, for your case, you could change the produces to 'application/json'. Unlike before,  only array and object are valid json. Now valid json values like int, string are also treated as valid json.

**Comment by ThePoShWolf** [comment]
@dolauli - Has that been resolved in a new version? I was originally using produces `application/json` and it would generate and build the module, but whenever a command was run that received a plain integer as the return, the cmdlet would error.

**Comment by dolauli** [comment]
Use 'application/json' and then run command below to use version 3.0.471 of autorest/powershell
`autorest --use:@autorest/powershell@3.0.471`

**Comment by ThePoShWolf** [comment]
Ah, brilliant. My test shows that to be successful. Thank you @dolauli !
