### ISSUE TITLE
Update operation support should be removed from reference doc of creation related cmdlets

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/autorest.powershell#899]
Description of creation operation cmdlets comes from the description of PUT operation on Swagger. Since PUT supports resource creation or update both by many services, it leads Azure PowerShell reference doc shows New-Az{Noun} cmdlet supports creation and update operation both. 

It is not accurate in many cases especially when service add additional logic on creation or update.  We should filter out "update" from reference doc or allow developer to customize reference doc.

**Comment by v-mosh21** [comment]
Hi @dingmeng-xue, thanks for checking this issue. I just want to point out that the Update-AzCloudService document also states it could create or update cloud service, but this cmdlet is used for update purpose not create. Thanks for your help!

Reference doc: https://docs.microsoft.com/en-us/powershell/module/az.cloudservice/update-azcloudservice?view=azps-7.2.0

**Comment by BethanyZhou** [comment]
Two requested features are supported in autorest.powershell v4
- Supported customizing description for cmdlet
- Filtered 'Create(s) or Update(s)' in description and replaced them by actual cmdlet action.
