### ISSUE TITLE
Generated modules fail to build when the response schema has a property named `body`

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#934]
Modules fail with `The type 'COMMANDNAME_CreateExpanded' already contains a definition for 'Body'` when the has schema contains a property named `body`.

For example, a path with a response object of:
``` yml
responses:
  '201':
    description: Created navigation property.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/microsoft.graph.todoTask'
```
where `#/components/schemas/microsoft.graph.todoTask` has a property named `body`:
``` yml
microsoft.graph.todoTask:
  allOf:
    - $ref: '#/components/schemas/microsoft.graph.entity'
    - title: todoTask
      type: object
      properties:
        body:
          $ref: '#/components/schemas/microsoft.graph.itemBody'
      additionalProperties:
        type: object
```

will fail at build time because the schema's `body` property conflicts with the `Body` property in the generated cmdlet class.
``` c#
/// <summary>Backing field for <see cref="Body" /> property.</summary>
private Sample.API.Models.IMicrosoftGraphTodoTask _body= new Sample.API.Models.MicrosoftGraphTodoTask();

/// <summary>todoTask</summary>
private Sample.API.Models.IMicrosoftGraphTodoTask Body { get => this._body; set => this._body = value; }

/// <summary>itemBody</summary>
[global::System.Management.Automation.Parameter(Mandatory = false, HelpMessage = "itemBody")]
[global::Sample.API.Category(global::Sample.API.ParameterCategory.Body)]
[Sample.API.Runtime.Info(
Required = false,
ReadOnly = false,
Description = @"itemBody",
SerializedName = @"body",
PossibleTypes = new [] { typeof(Sample.API.Models.IMicrosoftGraphItemBody) })]
public Sample.API.Models.IMicrosoftGraphItemBody Body { get => Body.Body ?? null /* object */; set => Body.Body = value; }
```
Microsoft Graph API has a lot of entities where `body` is a property name. e.g., [ToDoTask](https://docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0#properties) and [Message](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#properties).

### Repro Steps:
Using https://gist.github.com/peombwa/1f426dc4c1be72c448b3f6008bb8905e as the input file,
1. Run in an output directory
``` powershell
autorest --powershell --input-file:https://gist.github.com/peombwa/1f426dc4c1be72c448b3f6008bb8905e
```
2. Build generated module
``` powershell
 .\generated\build-module.ps1
```
3. Inspect build error
``` powershell
C:\tests\generated\generated\cmdlets\NewUserTodoListTask_CreateExpanded.cs(46,58): error CS0102: The type 'NewUserTodoListTask_CreateExpanded' already contains a definition for 'Body'
```
### Suggestion:
- Rename the `Body` property in the cmdlet class to something like `BodyObject` or `{SchemaName}Body` to avoid conflicts with schema property names.  Alternatively, we can provide a configuration that customers can use to specify an alternative name for the `Body` property in a cmdlet class.

### Environment Info:
``` powershell
➜ autorest --info
AutoRest code generation utility [cli version: 3.6.1; node: v14.18.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6306     C:\Users\user\.autorest\@autorest_core@3.0.6306
 core       @autorest/core                           3.8.3        C:\Users\user\.autorest\@autorest_core@3.8.3
 extension  @autorest/modelerfour                    4.15.414     C:\Users\user\.autorest\@autorest_modelerfour@4.15.414
 extension  @autorest/powershell                     3.0.483      C:\Users\user\.autorest\@autorest_powershell@3.0.483
 extension  @autorest/remodeler                      2.1.27       C:\Users\user\.autorest\@autorest_remodeler@2.1.27
```

**Comment by peombwa** [comment]
@dolauli, this still fails to build using the latest version of autoREST/PowerShell. It fails with the following error when running ` .\generated\build-module.ps1`:
``` powershell
Creating exports and docs...
$ParsingMetadataException/   at Sample.API.Runtime.PowerShell.ParameterGroup..ctor(String parameterName, Parameter[] parameters, String[] allVariantNames) in F:\M\tmp\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 204
   at Sample.API.Runtime.PowerShell.PsProxyTypeExtensions.<>c__DisplayClass7_0.<ToParameterGroups>b__3(IGrouping`2 pg) in F:\M\tmp\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 502
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Sample.API.Runtime.PowerShell.VariantGroup..ctor(String moduleName, String cmdletName, Variant[] variants, String outputFolder, String profileName, Boolean isTest, Boolean isInternal) in F:\M\tmp\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 68
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.<>c__DisplayClass36_2.<ProcessRecord>b__10(IGrouping`2 vg) in F:\M\tmp\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 69
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in F:\M\tmp\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 67
Export-ProxyCmdlet: F:\M\tmp\generated\build-module.ps1:132
Line |
 132 |    Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The parameter 'Body' has multiple parameter types [IMicrosoftGraphTodoTask, IMicrosoftGraphItemBody] defined, which
     | is not supported.
```

### Environment
``` powershell
➜ autorest --info
AutoRest code generation utility [cli version: 3.6.1; node: v14.11.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.8.4        C:\Users\peter\.autorest\@autorest_core@3.8.4
 extension  @autorest/modelerfour                    4.15.414     C:\Users\peter\.autorest\@autorest_modelerfour@4.15.414
 extension  @autorest/powershell                     3.0.485      C:\Users\peter\.autorest\@autorest_powershell@3.0.485
```

**Comment by dolauli** [comment]
I think the root cause is you keep both variants, one for expanded, the other for unexpanded. Our practice is to keep the expanded variant. So you will need to keep the 'COMMANDNAME_CreateExpanded' and remove the 'COMMANDNAME_Create' through directive.

**Comment by peombwa** [comment]
Removing `_Create` variant will not work for us since we use the variant to document snippets in our API reference docs for brevity - https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-beta&tabs=powershell#request-1.

The issue here is that `-BodyParameter` in AutoREST.PowerShell v2 got renamed to `-Body` in AutoREST.PowerShell v3 hence the conflict with schemas that have properties named `Body`. I understand that renaming `-Body` back to `-BodyParameter` or any other name would be considered a breaking change. To avoid this, I'd suggest we provide a configuration that customers can use to specify an alternative name for the `-Body` parameter if they intend to use it. Why generate `_Create` and `_CreateViaIdentity` variants only for them to be removed via directive?

@maisarissi, @ddyett, @darrelmiller, what's your thought on dropping support for `-BodyParameter`? This will mean:
- All POST, PUT, and PATCH snippets in the API reference will be inline/ [splattered](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2) (this poses a challenge for [openTypes](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=powershell#example) and [ByRef](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=powershell#request) operations)
-  Customers currently using `-BodyParameter` in their scripts will have to update their scipts.

**Comment by dolauli** [comment]
> @dolauli, removing `_Create` variant will not work for us since we use the variant to document snippets in our API reference docs for brevity - https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-beta&tabs=powershell#request-1.
> 
> The issue here is that `-BodyParameter` in AutoREST.PowerShell v2 got renamed to `-Body` in AutoREST.PowerShell v3 hence the conflict with schemas that have properties named `Body`. I understand that renaming `-Body` back to `-BodyParameter` or any other name would be considered a breaking change. To avoid this, I'd suggest we provide a configuration that customers can use to specify an alternative name for the `-Body` parameter if they intend to use it. Why generate `_Create` and `_CreateViaIdentity` variants only for them to be removed via directive?
> 
> @maisarissi, @ddyett, @darrelmiller, what's your thought on dropping support for `-BodyParameter`? This will mean:
> 
> * All POST, PUT, and PATCH snippets in the API reference will be inline/ [splattered](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2) (this poses a challenge for [openTypes](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=powershell#example) and [ByRef](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=powershell#request) operations)
> * Customers currently using `-BodyParameter` in their scripts will have to update their scipts.

@peombwa, you may use following directive to rename `-Body` back to `-BodyParameter` for the `_Create` and `_CreateViaidentity` and keep them. 
```
  - where:
      variant: Create|CreateViaIdentity
      parameter-name: Body
    set:
      parameter-name: BodyParameter
```

And besides, we generate two kinds of cmdlet - one flattened and the other un-flattened is because we want to give the developer the choice to pick either of them. For Azure PowerShell, we prefer to use the flattened way. And in some special case, we also keep the un-flattened cmdlet for customization.

**Comment by peombwa** [comment]
Thanks, @dolauli! The directive will do for now. We will explore the idea of just supporting flattened parameters soon.
