### ISSUE TITLE
Not able to load module correctly if path contains single quote.

### ISSUE THREAD

**Issue by Man2MSFT** [Azure/autorest.powershell#942]
As you can see in the image below, I have created a path which contains single quote in it(C:\Users\manojkumar\Documents\PowerShellTesting\team's size\4.3.1-preview\MicrosoftTeams). Users are facing issues during time of importing cmdlets which are AutoRest generated. Parsing error as you can see in the image below -

![image](https://user-images.githubusercontent.com/102780775/168812768-ac1cc758-81bd-4f2a-aeb5-571618c1854d.png)

It looks like it needs to be handle in PsHelper.cs file, as mentioned in the given image.
![image](https://user-images.githubusercontent.com/102780775/168813339-d09c1ea4-6f2d-4971-aa4b-a657dcc81d23.png)

**Comment by dolauli** [comment]
Fixed in https://www.npmjs.com/package/@autorest/powershell/v/3.0.490
