### ISSUE TITLE
`In` in `SignIn` is truncated from command names

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#955]
Given an `operationId` of `reports_ListApplicationSignInDetailedSummary`, AutoREST.PowerShell currently generates a command name of `Get-ReportApplicationSign` instead of `Get-ReportApplicationSignInDetailedSummary`. It looks like AutoREST.PowerShell treats the `In` in `SignIn` as a preposition thus truncating everything after the preposition in: https://github.com/Azure/autorest.powershell/blob/8baf63ed52e31aa70d91708832c2b3a3e290dbb6/powershell/plugins/create-commands-v2.ts#L80-L89.

#### Possible Solutions
- Exclude compound words such as `SignIn` and `SignOut` from being broken into two distinct words.
- Provide a configuration that customers can use to bypass the truncation of prepositions if they desire. Certain APIs use prepositions in their paths to communicate meaning. e.g., [https://graph.microsoft.com/v1.0/users/{id}/memberOf](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http).

#### Workaround
We can use rename directive to target the affected command variants and rename them to the proper name as a workaround. While this works well when targeting a handful of commands, it doesn't scale when the directive needs to be applied to hundreds of APIs/commands since we need to know ahead of time which command variants are affected.

**Comment by dingmeng-xue** [comment]
@dolauli , please look into it and fix it as soon as possible.
