### ISSUE TITLE
[Feature Request] OpenAPI `externalDocs` on an operation object support

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#960]
OpenAPI v3 specification supports [`externalDocs`](https://swagger.io/specification/#external-documentation-object) object that can be a property of `OpenAPI`, `Operation`, `Tag`, and `Schema` objects.

When `externalDocs` is present as a property of an `operation` object, we should parse the URL property of the `externalDocs` object and add it to the `.Link` section of the comment-based help. 

Given an OpenAPI file with an operation object of:
``` yml
# OpenAPI path object.
paths:
  /info.0.json:
    get:
      operationId: xkcd_getComicForToday
      externalDocs:
        url: 'https://xkcd.com/json.html'
      description: |
        Fetch current comic and metadata.
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/comic'
```
We should generate the following comment-based help:
``` powershell
<#
.Synopsis
Fetch current comic and metadata.
.Inputs
Sample.API.Models.IXkcdIdentity
.Outputs
Sample.API.Models.IComic
.Link
https://docs.microsoft.com/en-us/powershell/module/xkcd/get-xkcdcomic
.Link
https://xkcd.com/json.html
#>
function Get-XkcdComic {
[OutputType([Sample.API.Models.IComic])]
[CmdletBinding(DefaultParameterSetName='Get', PositionalBinding=$false)]
param(
...
```

The `.Link` from the `externalDocs.Url` should be placed below the PowerShell module browser link for `Get-Help -Online` to point to the PowerShell module browser link as shown above. PowerShell supports multiple `.Link` in the comment-based help. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.2#link.

**Comment by maisarissi** [comment]
Hi @dingmeng-xue @BethanyZhou @dolauli . As part of our PowerShell documentation completeness story, we want to add external links so we can point folks to the Microsoft Graph docs page (or any other external documentation) where they can find even more information around the APIs/parameter/get examples.

Can we get this prioritized?

**Comment by dingmeng-xue** [comment]
@dolauli , could you check Azure practice? Will it support `externalDocs`? if developer want to add additional links of external Docs, how to define that in README.md?

**Comment by dolauli** [comment]
@dingmeng-xue,  For Azure services, we also have externalDocs as below in some services. But currently we do not export these urls in .Link of the help. The question here would be whether we should export these urls in .Link for all the services or just for MS graph. Looks a reasonable solution is that we add a config in readme.md to let developers to choose whether to export them.
```
        "externalDocs": {
          "url": "http://msdn.microsoft.com/en-us/library/windowsazure/jj870968.aspx"
        }
```

**Comment by dingmeng-xue** [comment]
If it is not widely used by Azure API spec, let us add externalDocs as default.

**Comment by maisarissi** [comment]
Can we get an estimate when you will work on this feature?

**Comment by dolauli** [comment]
It will be added in autorest.powershel 4.x, which is expected to be release at the end of this semester.

**Comment by maisarissi** [comment]
Would it be possible to also add this functionality to AutoREST.PowerShell v3? We have a new Graph PowerShell v2 preview version we have plans to GA by EOY that uses AutoREST v3.
Also, is there any documentation about AutoREST.PowerShell v4 where we can see the features and breaking changes?

**Comment by BethanyZhou** [comment]
This feature has been supported in v3 and v4 both, see PR https://github.com/Azure/autorest.powershell/pull/1004 and https://github.com/Azure/autorest.powershell/pull/1016

**Comment by peombwa** [comment]
@BethanyZhou, thanks for the update! The change is not present in v3. PR #1004 to v3 was reverted in PR #1015. Will the change be reapplied to v3?

**Comment by dolauli** [comment]
My bad. It will not be applied to v3.

**Comment by maisarissi** [comment]
Hey @dolauli 
Why the changes were reverted? Was there any bugs created per the externalDocs support in v3?

**Comment by dolauli** [comment]
It is a feature planned for v4 and was wrongly merged into main by a mistake.

**Comment by maisarissi** [comment]
Got it. Is this a breaking change for those using v3? The Microsoft Graph PowerShell SDK just updated its dependencies to target AutoREST v3 and since v4 it is not yet GA, would be possible to also include this feature as part of v3?
