### ISSUE TITLE
CS1525, CS1073, CS1056 errors during build-module

### ISSUE THREAD

**Issue by progmatic73** [Azure/autorest.powershell#964]
Hello,  when running _.\generated\build-module.ps1 -run_ I get:

error CS1525: Invalid expression term ''
error CS1073: Unexpected token '$'
error CS1056: Unexpected character '$'

I removed all but one path from the original api to troubleshoot located here: https://gist.github.com/progmatic73/20921b1c0d20d0697edcec7a0226c9b6

**Comment by dolauli** [comment]
Your swagger is missing of the servers configuration. e.g. as below.
```
servers:
  - url: https://example.com
```

**Comment by soroshsabz** [comment]
ITNOA

@dolauli very very thanks

But I think autorest must be have better error message
