### ISSUE TITLE
"TotalIops" in generated code should not be convert to "TotalIop"

### ISSUE THREAD

**Issue by blueww** [Azure/autorest.powershell#965]
Swagger has a property "TotalIops" in server returned Elastic San object, but for some reasons in the powershell cmdlets response it is just showing as "TotalIop".

Swagger https://github.com/Azure/azure-rest-api-specs/blob/main/specification/elasticsan/resource-manager/Microsoft.ElasticSan/preview/2021-11-20-preview/elasticsan.json#:~:text=%22totalIops%22%3A%20%7B,%22readOnly 

![image](https://user-images.githubusercontent.com/6926193/177072612-1d7e4fb6-e40f-4b0c-91dd-ca4dc6ded138.png)

This might caused by Powershell cmdlet should have input parameter as singleton.
But this case it should not be "TotalIop", since:
1. "Iops" (io per second) is a term, which should not be singularized to "Ipo".
2. It is only for output. Output should not be singularize , only input should.

**Comment by dingmeng-xue** [comment]
There is no total solution to detect correct singular and plural. It relies on directive settings. Close this request because of priority.
