### ISSUE TITLE
Is there a way to add version as an input while generating or building commandlets

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#967]
I am using autorest for SDK generation and the commands version is always 0.1.0. Is there a way to add that?

**Comment by dolauli** [comment]
You may create a readme.md, and put all the configurations in it. And you may configure the module version as below.
```
module-version: 1.1.0
```

**Comment by JnaneshD05** [comment]
Thanks for the help

**Comment by JnaneshD05** [comment]
Can you also suggest if there is a way of grouping the only certain generated commandlets based on a tag?
