### ISSUE TITLE
Need help in understanding how to use pass the body in commandlet

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#975]
I have generated the SDK using openapi and trying out the command new-user with a request body in PSObject type. If I pass this as the request body I get the error. 
New-User: Cannot process argument transformation on parameter 'Users'. Cannot convert the "@{email=PAPI1_e@papi.com; fullName=PAPI1_e; name=PAPI1_e; userGroups=System.Object[]; useSystemGeneratePassword=False; password=xxxx; inviteUser=False}" value of type "System.Management.Automation.PSCustomObject" to type "Commvault.Powershell.Models.ICreateUser".

Please help with this

**Comment by dingmeng-xue** [comment]
@JnaneshD05 , thanks for contacting us. Could you provide generated cmdlet syntax to us for reference?

**Comment by dolauli** [comment]
Close it since no feedback from authors.
