### ISSUE TITLE
[Feature]: Pagination nextLink Validation of empty string

### ISSUE THREAD

**Issue by kaushal087** [Azure/autorest.powershell#982]
### Description of the new feature

Currently in List API where pagination is being used, nextLink validation is done. 

Currently, it has a check like this:

```
(if nextLink != null ){
    <call next page URL>
}
 ```

Many services use nextLink="" when there are no more page, in this case it enters in `if` and calls the empty URL. 

The feature request is to change it to:

```
(if nextLink != null  and nextLink != ""){
    <call next page URL>
}
 ```

**Comment by dolauli** [comment]
Fixed in autorest.powershell v4.
