### ISSUE TITLE
Few part of the output not visible to the end user .

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#987]
We have a schema similar to the below mentioned : for a particular API response:
{
            "topology": {
                "id": 23,
                "name": "aata"
            },
            "topologyType": "ONE_WAY",
            "clientType": "SERVER"
 }
 
The commandlet which is generated for this API shows only topologyType and clientType 
 
![image](https://user-images.githubusercontent.com/97098752/184469994-b9b864ca-f907-4b2e-a37e-8dc01a18e0c5.png)

Unless we do the format-list or format-table we can't see the topologyId and topologyName 

      
![image](https://user-images.githubusercontent.com/97098752/184470015-5c1b581e-9e24-42d1-b7ea-c130c66a9a72.png)

Any suggestions to overcome this via directive or other would be appreciated.

**Comment by dolauli** [comment]
By default, only direct primitive member of the return object will be displayed. You may add more through a directive. Please see https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#Table-Formatting for details.
