### ISSUE TITLE
Command output not shown if there are more than 2 levels in json

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#995]
The formatting doesn't output the response when it is of multi level and quite big schema . Need help in disabling table formatting in directive. The example shows how to disable for one model.

**Comment by JnaneshD05** [comment]
Can anyone help in checking this please? Is there a way we can convert this to json for all commands through custom code maybe?

**Comment by JnaneshD05** [comment]
Thanks for the reply. I tried with suppressing few models. Still they will not be shown to the user if json levels are more. It just outputs model name. But if we convert it to json we can see easily. Let me know if we have a way to solve this

**Comment by dolauli** [comment]
Try to add following code in the readme.md.
```
nested-object-to-string: true
```
